cargo-features = ["profile-rustflags"]

[package]
name = "res"
version = "0.1.0"
authors = ["Steven Cole <scole66@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0"

[dependencies]
num = "0.3"
libc = "0.2"
itertools = "0.10.0"
#lasso = "0.5.0"
ahash = "0.7.2"
lazy_static = "1.4.0"
regex = "1"
uid = "0.1.5"
counter = "0.5.3"
anyhow = "1.0.56"
num_enum = "0.5.7"
bimap = "0.6.2"

[dev-dependencies]
test-case = "2.0"

[profile.coverage]
inherits = "dev"
rustflags = [ "-Cinstrument-coverage" ]
