[package]
name = "res"
version = "0.1.0"
authors = ["Steven Cole <scole66@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grcov = "0.5.15"
num = "0.3"
