max_width = 120
#width_heuristics = { fn_call_width = 120, attr_fn_like_width = 120, struct_lit_width=120, struct_variant_width=120,array_width=120,chain_width=120,single_line_if_else_max_width=120 }
use_small_heuristics = "Max"
