// DO NOT EDIT THIS FILE. IT WAS AUTOMATICALLY GENERATED BY:
//
//   ucd-generate script unicode
//
// Unicode version: 17.0.0.
//
// ucd-generate 0.3.1 is available on crates.io.

pub(crate) const BY_NAME: &'static [(&'static str, &'static [(u32, u32)])] = &[
    ("Adlam", ADLAM),
    ("Ahom", AHOM),
    ("Anatolian_Hieroglyphs", ANATOLIAN_HIEROGLYPHS),
    ("Arabic", ARABIC),
    ("Armenian", ARMENIAN),
    ("Avestan", AVESTAN),
    ("Balinese", BALINESE),
    ("Bamum", BAMUM),
    ("Bassa_Vah", BASSA_VAH),
    ("Batak", BATAK),
    ("Bengali", BENGALI),
    ("Beria_Erfe", BERIA_ERFE),
    ("Bhaiksuki", BHAIKSUKI),
    ("Bopomofo", BOPOMOFO),
    ("Brahmi", BRAHMI),
    ("Braille", BRAILLE),
    ("Buginese", BUGINESE),
    ("Buhid", BUHID),
    ("Canadian_Aboriginal", CANADIAN_ABORIGINAL),
    ("Carian", CARIAN),
    ("Caucasian_Albanian", CAUCASIAN_ALBANIAN),
    ("Chakma", CHAKMA),
    ("Cham", CHAM),
    ("Cherokee", CHEROKEE),
    ("Chorasmian", CHORASMIAN),
    ("Common", COMMON),
    ("Coptic", COPTIC),
    ("Cuneiform", CUNEIFORM),
    ("Cypriot", CYPRIOT),
    ("Cypro_Minoan", CYPRO_MINOAN),
    ("Cyrillic", CYRILLIC),
    ("Deseret", DESERET),
    ("Devanagari", DEVANAGARI),
    ("Dives_Akuru", DIVES_AKURU),
    ("Dogra", DOGRA),
    ("Duployan", DUPLOYAN),
    ("Egyptian_Hieroglyphs", EGYPTIAN_HIEROGLYPHS),
    ("Elbasan", ELBASAN),
    ("Elymaic", ELYMAIC),
    ("Ethiopic", ETHIOPIC),
    ("Garay", GARAY),
    ("Georgian", GEORGIAN),
    ("Glagolitic", GLAGOLITIC),
    ("Gothic", GOTHIC),
    ("Grantha", GRANTHA),
    ("Greek", GREEK),
    ("Gujarati", GUJARATI),
    ("Gunjala_Gondi", GUNJALA_GONDI),
    ("Gurmukhi", GURMUKHI),
    ("Gurung_Khema", GURUNG_KHEMA),
    ("Han", HAN),
    ("Hangul", HANGUL),
    ("Hanifi_Rohingya", HANIFI_ROHINGYA),
    ("Hanunoo", HANUNOO),
    ("Hatran", HATRAN),
    ("Hebrew", HEBREW),
    ("Hiragana", HIRAGANA),
    ("Imperial_Aramaic", IMPERIAL_ARAMAIC),
    ("Inherited", INHERITED),
    ("Inscriptional_Pahlavi", INSCRIPTIONAL_PAHLAVI),
    ("Inscriptional_Parthian", INSCRIPTIONAL_PARTHIAN),
    ("Javanese", JAVANESE),
    ("Kaithi", KAITHI),
    ("Kannada", KANNADA),
    ("Katakana", KATAKANA),
    ("Kawi", KAWI),
    ("Kayah_Li", KAYAH_LI),
    ("Kharoshthi", KHAROSHTHI),
    ("Khitan_Small_Script", KHITAN_SMALL_SCRIPT),
    ("Khmer", KHMER),
    ("Khojki", KHOJKI),
    ("Khudawadi", KHUDAWADI),
    ("Kirat_Rai", KIRAT_RAI),
    ("Lao", LAO),
    ("Latin", LATIN),
    ("Lepcha", LEPCHA),
    ("Limbu", LIMBU),
    ("Linear_A", LINEAR_A),
    ("Linear_B", LINEAR_B),
    ("Lisu", LISU),
    ("Lycian", LYCIAN),
    ("Lydian", LYDIAN),
    ("Mahajani", MAHAJANI),
    ("Makasar", MAKASAR),
    ("Malayalam", MALAYALAM),
    ("Mandaic", MANDAIC),
    ("Manichaean", MANICHAEAN),
    ("Marchen", MARCHEN),
    ("Masaram_Gondi", MASARAM_GONDI),
    ("Medefaidrin", MEDEFAIDRIN),
    ("Meetei_Mayek", MEETEI_MAYEK),
    ("Mende_Kikakui", MENDE_KIKAKUI),
    ("Meroitic_Cursive", MEROITIC_CURSIVE),
    ("Meroitic_Hieroglyphs", MEROITIC_HIEROGLYPHS),
    ("Miao", MIAO),
    ("Modi", MODI),
    ("Mongolian", MONGOLIAN),
    ("Mro", MRO),
    ("Multani", MULTANI),
    ("Myanmar", MYANMAR),
    ("Nabataean", NABATAEAN),
    ("Nag_Mundari", NAG_MUNDARI),
    ("Nandinagari", NANDINAGARI),
    ("New_Tai_Lue", NEW_TAI_LUE),
    ("Newa", NEWA),
    ("Nko", NKO),
    ("Nushu", NUSHU),
    ("Nyiakeng_Puachue_Hmong", NYIAKENG_PUACHUE_HMONG),
    ("Ogham", OGHAM),
    ("Ol_Chiki", OL_CHIKI),
    ("Ol_Onal", OL_ONAL),
    ("Old_Hungarian", OLD_HUNGARIAN),
    ("Old_Italic", OLD_ITALIC),
    ("Old_North_Arabian", OLD_NORTH_ARABIAN),
    ("Old_Permic", OLD_PERMIC),
    ("Old_Persian", OLD_PERSIAN),
    ("Old_Sogdian", OLD_SOGDIAN),
    ("Old_South_Arabian", OLD_SOUTH_ARABIAN),
    ("Old_Turkic", OLD_TURKIC),
    ("Old_Uyghur", OLD_UYGHUR),
    ("Oriya", ORIYA),
    ("Osage", OSAGE),
    ("Osmanya", OSMANYA),
    ("Pahawh_Hmong", PAHAWH_HMONG),
    ("Palmyrene", PALMYRENE),
    ("Pau_Cin_Hau", PAU_CIN_HAU),
    ("Phags_Pa", PHAGS_PA),
    ("Phoenician", PHOENICIAN),
    ("Psalter_Pahlavi", PSALTER_PAHLAVI),
    ("Rejang", REJANG),
    ("Runic", RUNIC),
    ("Samaritan", SAMARITAN),
    ("Saurashtra", SAURASHTRA),
    ("Sharada", SHARADA),
    ("Shavian", SHAVIAN),
    ("Siddham", SIDDHAM),
    ("Sidetic", SIDETIC),
    ("SignWriting", SIGNWRITING),
    ("Sinhala", SINHALA),
    ("Sogdian", SOGDIAN),
    ("Sora_Sompeng", SORA_SOMPENG),
    ("Soyombo", SOYOMBO),
    ("Sundanese", SUNDANESE),
    ("Sunuwar", SUNUWAR),
    ("Syloti_Nagri", SYLOTI_NAGRI),
    ("Syriac", SYRIAC),
    ("Tagalog", TAGALOG),
    ("Tagbanwa", TAGBANWA),
    ("Tai_Le", TAI_LE),
    ("Tai_Tham", TAI_THAM),
    ("Tai_Viet", TAI_VIET),
    ("Tai_Yo", TAI_YO),
    ("Takri", TAKRI),
    ("Tamil", TAMIL),
    ("Tangsa", TANGSA),
    ("Tangut", TANGUT),
    ("Telugu", TELUGU),
    ("Thaana", THAANA),
    ("Thai", THAI),
    ("Tibetan", TIBETAN),
    ("Tifinagh", TIFINAGH),
    ("Tirhuta", TIRHUTA),
    ("Todhri", TODHRI),
    ("Tolong_Siki", TOLONG_SIKI),
    ("Toto", TOTO),
    ("Tulu_Tigalari", TULU_TIGALARI),
    ("Ugaritic", UGARITIC),
    ("Vai", VAI),
    ("Vithkuqi", VITHKUQI),
    ("Wancho", WANCHO),
    ("Warang_Citi", WARANG_CITI),
    ("Yezidi", YEZIDI),
    ("Yi", YI),
    ("Zanabazar_Square", ZANABAZAR_SQUARE),
];

pub(crate) const ADLAM: &'static [(u32, u32)] = &[(125184, 125259), (125264, 125273), (125278, 125279)];

pub(crate) const AHOM: &'static [(u32, u32)] = &[(71424, 71450), (71453, 71467), (71472, 71494)];

pub(crate) const ANATOLIAN_HIEROGLYPHS: &'static [(u32, u32)] = &[(82944, 83526)];

pub(crate) const ARABIC: &'static [(u32, u32)] = &[
    (1536, 1540),
    (1542, 1547),
    (1549, 1562),
    (1564, 1566),
    (1568, 1599),
    (1601, 1610),
    (1622, 1647),
    (1649, 1756),
    (1758, 1791),
    (1872, 1919),
    (2160, 2193),
    (2199, 2273),
    (2275, 2303),
    (64336, 64829),
    (64832, 64975),
    (65008, 65023),
    (65136, 65140),
    (65142, 65276),
    (69216, 69246),
    (69314, 69319),
    (69328, 69336),
    (69370, 69375),
    (126464, 126467),
    (126469, 126495),
    (126497, 126498),
    (126500, 126500),
    (126503, 126503),
    (126505, 126514),
    (126516, 126519),
    (126521, 126521),
    (126523, 126523),
    (126530, 126530),
    (126535, 126535),
    (126537, 126537),
    (126539, 126539),
    (126541, 126543),
    (126545, 126546),
    (126548, 126548),
    (126551, 126551),
    (126553, 126553),
    (126555, 126555),
    (126557, 126557),
    (126559, 126559),
    (126561, 126562),
    (126564, 126564),
    (126567, 126570),
    (126572, 126578),
    (126580, 126583),
    (126585, 126588),
    (126590, 126590),
    (126592, 126601),
    (126603, 126619),
    (126625, 126627),
    (126629, 126633),
    (126635, 126651),
    (126704, 126705),
];

pub(crate) const ARMENIAN: &'static [(u32, u32)] = &[(1329, 1366), (1369, 1418), (1421, 1423), (64275, 64279)];

pub(crate) const AVESTAN: &'static [(u32, u32)] = &[(68352, 68405), (68409, 68415)];

pub(crate) const BALINESE: &'static [(u32, u32)] = &[(6912, 6988), (6990, 7039)];

pub(crate) const BAMUM: &'static [(u32, u32)] = &[(42656, 42743), (92160, 92728)];

pub(crate) const BASSA_VAH: &'static [(u32, u32)] = &[(92880, 92909), (92912, 92917)];

pub(crate) const BATAK: &'static [(u32, u32)] = &[(7104, 7155), (7164, 7167)];

pub(crate) const BENGALI: &'static [(u32, u32)] = &[
    (2432, 2435),
    (2437, 2444),
    (2447, 2448),
    (2451, 2472),
    (2474, 2480),
    (2482, 2482),
    (2486, 2489),
    (2492, 2500),
    (2503, 2504),
    (2507, 2510),
    (2519, 2519),
    (2524, 2525),
    (2527, 2531),
    (2534, 2558),
];

pub(crate) const BERIA_ERFE: &'static [(u32, u32)] = &[(93856, 93880), (93883, 93907)];

pub(crate) const BHAIKSUKI: &'static [(u32, u32)] = &[(72704, 72712), (72714, 72758), (72760, 72773), (72784, 72812)];

pub(crate) const BOPOMOFO: &'static [(u32, u32)] = &[(746, 747), (12549, 12591), (12704, 12735)];

pub(crate) const BRAHMI: &'static [(u32, u32)] = &[(69632, 69709), (69714, 69749), (69759, 69759)];

pub(crate) const BRAILLE: &'static [(u32, u32)] = &[(10240, 10495)];

pub(crate) const BUGINESE: &'static [(u32, u32)] = &[(6656, 6683), (6686, 6687)];

pub(crate) const BUHID: &'static [(u32, u32)] = &[(5952, 5971)];

pub(crate) const CANADIAN_ABORIGINAL: &'static [(u32, u32)] = &[(5120, 5759), (6320, 6389), (72368, 72383)];

pub(crate) const CARIAN: &'static [(u32, u32)] = &[(66208, 66256)];

pub(crate) const CAUCASIAN_ALBANIAN: &'static [(u32, u32)] = &[(66864, 66915), (66927, 66927)];

pub(crate) const CHAKMA: &'static [(u32, u32)] = &[(69888, 69940), (69942, 69959)];

pub(crate) const CHAM: &'static [(u32, u32)] = &[(43520, 43574), (43584, 43597), (43600, 43609), (43612, 43615)];

pub(crate) const CHEROKEE: &'static [(u32, u32)] = &[(5024, 5109), (5112, 5117), (43888, 43967)];

pub(crate) const CHORASMIAN: &'static [(u32, u32)] = &[(69552, 69579)];

pub(crate) const COMMON: &'static [(u32, u32)] = &[
    (0, 64),
    (91, 96),
    (123, 169),
    (171, 185),
    (187, 191),
    (215, 215),
    (247, 247),
    (697, 735),
    (741, 745),
    (748, 767),
    (884, 884),
    (894, 894),
    (901, 901),
    (903, 903),
    (1541, 1541),
    (1548, 1548),
    (1563, 1563),
    (1567, 1567),
    (1600, 1600),
    (1757, 1757),
    (2274, 2274),
    (2404, 2405),
    (3647, 3647),
    (4053, 4056),
    (4347, 4347),
    (5867, 5869),
    (5941, 5942),
    (6146, 6147),
    (6149, 6149),
    (7379, 7379),
    (7393, 7393),
    (7401, 7404),
    (7406, 7411),
    (7413, 7415),
    (7418, 7418),
    (8192, 8203),
    (8206, 8292),
    (8294, 8304),
    (8308, 8318),
    (8320, 8334),
    (8352, 8385),
    (8448, 8485),
    (8487, 8489),
    (8492, 8497),
    (8499, 8525),
    (8527, 8543),
    (8585, 8587),
    (8592, 9257),
    (9280, 9290),
    (9312, 10239),
    (10496, 11123),
    (11126, 11263),
    (11776, 11869),
    (12272, 12292),
    (12294, 12294),
    (12296, 12320),
    (12336, 12343),
    (12348, 12351),
    (12443, 12444),
    (12448, 12448),
    (12539, 12540),
    (12688, 12703),
    (12736, 12773),
    (12783, 12783),
    (12832, 12895),
    (12927, 13007),
    (13055, 13055),
    (13144, 13311),
    (19904, 19967),
    (42752, 42785),
    (42888, 42890),
    (43056, 43065),
    (43310, 43310),
    (43471, 43471),
    (43867, 43867),
    (43882, 43883),
    (64830, 64831),
    (65040, 65049),
    (65072, 65106),
    (65108, 65126),
    (65128, 65131),
    (65279, 65279),
    (65281, 65312),
    (65339, 65344),
    (65371, 65381),
    (65392, 65392),
    (65438, 65439),
    (65504, 65510),
    (65512, 65518),
    (65529, 65533),
    (65792, 65794),
    (65799, 65843),
    (65847, 65855),
    (65936, 65948),
    (66000, 66044),
    (66273, 66299),
    (113824, 113827),
    (117760, 118012),
    (118016, 118451),
    (118458, 118480),
    (118496, 118512),
    (118608, 118723),
    (118784, 119029),
    (119040, 119078),
    (119081, 119142),
    (119146, 119162),
    (119171, 119172),
    (119180, 119209),
    (119214, 119274),
    (119488, 119507),
    (119520, 119539),
    (119552, 119638),
    (119648, 119672),
    (119808, 119892),
    (119894, 119964),
    (119966, 119967),
    (119970, 119970),
    (119973, 119974),
    (119977, 119980),
    (119982, 119993),
    (119995, 119995),
    (119997, 120003),
    (120005, 120069),
    (120071, 120074),
    (120077, 120084),
    (120086, 120092),
    (120094, 120121),
    (120123, 120126),
    (120128, 120132),
    (120134, 120134),
    (120138, 120144),
    (120146, 120485),
    (120488, 120779),
    (120782, 120831),
    (126065, 126132),
    (126209, 126269),
    (126976, 127019),
    (127024, 127123),
    (127136, 127150),
    (127153, 127167),
    (127169, 127183),
    (127185, 127221),
    (127232, 127405),
    (127462, 127487),
    (127489, 127490),
    (127504, 127547),
    (127552, 127560),
    (127568, 127569),
    (127584, 127589),
    (127744, 128728),
    (128732, 128748),
    (128752, 128764),
    (128768, 128985),
    (128992, 129003),
    (129008, 129008),
    (129024, 129035),
    (129040, 129095),
    (129104, 129113),
    (129120, 129159),
    (129168, 129197),
    (129200, 129211),
    (129216, 129217),
    (129232, 129240),
    (129280, 129623),
    (129632, 129645),
    (129648, 129660),
    (129664, 129674),
    (129678, 129734),
    (129736, 129736),
    (129741, 129756),
    (129759, 129770),
    (129775, 129784),
    (129792, 129938),
    (129940, 130042),
    (917505, 917505),
    (917536, 917631),
];

pub(crate) const COPTIC: &'static [(u32, u32)] = &[(994, 1007), (11392, 11507), (11513, 11519)];

pub(crate) const CUNEIFORM: &'static [(u32, u32)] = &[(73728, 74649), (74752, 74862), (74864, 74868), (74880, 75075)];

pub(crate) const CYPRIOT: &'static [(u32, u32)] =
    &[(67584, 67589), (67592, 67592), (67594, 67637), (67639, 67640), (67644, 67644), (67647, 67647)];

pub(crate) const CYPRO_MINOAN: &'static [(u32, u32)] = &[(77712, 77810)];

pub(crate) const CYRILLIC: &'static [(u32, u32)] = &[
    (1024, 1156),
    (1159, 1327),
    (7296, 7306),
    (7467, 7467),
    (7544, 7544),
    (11744, 11775),
    (42560, 42655),
    (65070, 65071),
    (122928, 122989),
    (123023, 123023),
];

pub(crate) const DESERET: &'static [(u32, u32)] = &[(66560, 66639)];

pub(crate) const DEVANAGARI: &'static [(u32, u32)] =
    &[(2304, 2384), (2389, 2403), (2406, 2431), (43232, 43263), (72448, 72457)];

pub(crate) const DIVES_AKURU: &'static [(u32, u32)] = &[
    (71936, 71942),
    (71945, 71945),
    (71948, 71955),
    (71957, 71958),
    (71960, 71989),
    (71991, 71992),
    (71995, 72006),
    (72016, 72025),
];

pub(crate) const DOGRA: &'static [(u32, u32)] = &[(71680, 71739)];

pub(crate) const DUPLOYAN: &'static [(u32, u32)] =
    &[(113664, 113770), (113776, 113788), (113792, 113800), (113808, 113817), (113820, 113823)];

pub(crate) const EGYPTIAN_HIEROGLYPHS: &'static [(u32, u32)] = &[(77824, 78933), (78944, 82938)];

pub(crate) const ELBASAN: &'static [(u32, u32)] = &[(66816, 66855)];

pub(crate) const ELYMAIC: &'static [(u32, u32)] = &[(69600, 69622)];

pub(crate) const ETHIOPIC: &'static [(u32, u32)] = &[
    (4608, 4680),
    (4682, 4685),
    (4688, 4694),
    (4696, 4696),
    (4698, 4701),
    (4704, 4744),
    (4746, 4749),
    (4752, 4784),
    (4786, 4789),
    (4792, 4798),
    (4800, 4800),
    (4802, 4805),
    (4808, 4822),
    (4824, 4880),
    (4882, 4885),
    (4888, 4954),
    (4957, 4988),
    (4992, 5017),
    (11648, 11670),
    (11680, 11686),
    (11688, 11694),
    (11696, 11702),
    (11704, 11710),
    (11712, 11718),
    (11720, 11726),
    (11728, 11734),
    (11736, 11742),
    (43777, 43782),
    (43785, 43790),
    (43793, 43798),
    (43808, 43814),
    (43816, 43822),
    (124896, 124902),
    (124904, 124907),
    (124909, 124910),
    (124912, 124926),
];

pub(crate) const GARAY: &'static [(u32, u32)] = &[(68928, 68965), (68969, 68997), (69006, 69007)];

pub(crate) const GEORGIAN: &'static [(u32, u32)] = &[
    (4256, 4293),
    (4295, 4295),
    (4301, 4301),
    (4304, 4346),
    (4348, 4351),
    (7312, 7354),
    (7357, 7359),
    (11520, 11557),
    (11559, 11559),
    (11565, 11565),
];

pub(crate) const GLAGOLITIC: &'static [(u32, u32)] =
    &[(11264, 11359), (122880, 122886), (122888, 122904), (122907, 122913), (122915, 122916), (122918, 122922)];

pub(crate) const GOTHIC: &'static [(u32, u32)] = &[(66352, 66378)];

pub(crate) const GRANTHA: &'static [(u32, u32)] = &[
    (70400, 70403),
    (70405, 70412),
    (70415, 70416),
    (70419, 70440),
    (70442, 70448),
    (70450, 70451),
    (70453, 70457),
    (70460, 70468),
    (70471, 70472),
    (70475, 70477),
    (70480, 70480),
    (70487, 70487),
    (70493, 70499),
    (70502, 70508),
    (70512, 70516),
];

pub(crate) const GREEK: &'static [(u32, u32)] = &[
    (880, 883),
    (885, 887),
    (890, 893),
    (895, 895),
    (900, 900),
    (902, 902),
    (904, 906),
    (908, 908),
    (910, 929),
    (931, 993),
    (1008, 1023),
    (7462, 7466),
    (7517, 7521),
    (7526, 7530),
    (7615, 7615),
    (7936, 7957),
    (7960, 7965),
    (7968, 8005),
    (8008, 8013),
    (8016, 8023),
    (8025, 8025),
    (8027, 8027),
    (8029, 8029),
    (8031, 8061),
    (8064, 8116),
    (8118, 8132),
    (8134, 8147),
    (8150, 8155),
    (8157, 8175),
    (8178, 8180),
    (8182, 8190),
    (8486, 8486),
    (43877, 43877),
    (65856, 65934),
    (65952, 65952),
    (119296, 119365),
];

pub(crate) const GUJARATI: &'static [(u32, u32)] = &[
    (2689, 2691),
    (2693, 2701),
    (2703, 2705),
    (2707, 2728),
    (2730, 2736),
    (2738, 2739),
    (2741, 2745),
    (2748, 2757),
    (2759, 2761),
    (2763, 2765),
    (2768, 2768),
    (2784, 2787),
    (2790, 2801),
    (2809, 2815),
];

pub(crate) const GUNJALA_GONDI: &'static [(u32, u32)] =
    &[(73056, 73061), (73063, 73064), (73066, 73102), (73104, 73105), (73107, 73112), (73120, 73129)];

pub(crate) const GURMUKHI: &'static [(u32, u32)] = &[
    (2561, 2563),
    (2565, 2570),
    (2575, 2576),
    (2579, 2600),
    (2602, 2608),
    (2610, 2611),
    (2613, 2614),
    (2616, 2617),
    (2620, 2620),
    (2622, 2626),
    (2631, 2632),
    (2635, 2637),
    (2641, 2641),
    (2649, 2652),
    (2654, 2654),
    (2662, 2678),
];

pub(crate) const GURUNG_KHEMA: &'static [(u32, u32)] = &[(90368, 90425)];

pub(crate) const HAN: &'static [(u32, u32)] = &[
    (11904, 11929),
    (11931, 12019),
    (12032, 12245),
    (12293, 12293),
    (12295, 12295),
    (12321, 12329),
    (12344, 12347),
    (13312, 19903),
    (19968, 40959),
    (63744, 64109),
    (64112, 64217),
    (94178, 94179),
    (94192, 94198),
    (131072, 173791),
    (173824, 178205),
    (178208, 183981),
    (183984, 191456),
    (191472, 192093),
    (194560, 195101),
    (196608, 201546),
    (201552, 210041),
];

pub(crate) const HANGUL: &'static [(u32, u32)] = &[
    (4352, 4607),
    (12334, 12335),
    (12593, 12686),
    (12800, 12830),
    (12896, 12926),
    (43360, 43388),
    (44032, 55203),
    (55216, 55238),
    (55243, 55291),
    (65440, 65470),
    (65474, 65479),
    (65482, 65487),
    (65490, 65495),
    (65498, 65500),
];

pub(crate) const HANIFI_ROHINGYA: &'static [(u32, u32)] = &[(68864, 68903), (68912, 68921)];

pub(crate) const HANUNOO: &'static [(u32, u32)] = &[(5920, 5940)];

pub(crate) const HATRAN: &'static [(u32, u32)] = &[(67808, 67826), (67828, 67829), (67835, 67839)];

pub(crate) const HEBREW: &'static [(u32, u32)] = &[
    (1425, 1479),
    (1488, 1514),
    (1519, 1524),
    (64285, 64310),
    (64312, 64316),
    (64318, 64318),
    (64320, 64321),
    (64323, 64324),
    (64326, 64335),
];

pub(crate) const HIRAGANA: &'static [(u32, u32)] =
    &[(12353, 12438), (12445, 12447), (110593, 110879), (110898, 110898), (110928, 110930), (127488, 127488)];

pub(crate) const IMPERIAL_ARAMAIC: &'static [(u32, u32)] = &[(67648, 67669), (67671, 67679)];

pub(crate) const INHERITED: &'static [(u32, u32)] = &[
    (768, 879),
    (1157, 1158),
    (1611, 1621),
    (1648, 1648),
    (2385, 2388),
    (6832, 6877),
    (6880, 6891),
    (7376, 7378),
    (7380, 7392),
    (7394, 7400),
    (7405, 7405),
    (7412, 7412),
    (7416, 7417),
    (7616, 7679),
    (8204, 8205),
    (8400, 8432),
    (12330, 12333),
    (12441, 12442),
    (65024, 65039),
    (65056, 65069),
    (66045, 66045),
    (66272, 66272),
    (70459, 70459),
    (118528, 118573),
    (118576, 118598),
    (119143, 119145),
    (119163, 119170),
    (119173, 119179),
    (119210, 119213),
    (917760, 917999),
];

pub(crate) const INSCRIPTIONAL_PAHLAVI: &'static [(u32, u32)] = &[(68448, 68466), (68472, 68479)];

pub(crate) const INSCRIPTIONAL_PARTHIAN: &'static [(u32, u32)] = &[(68416, 68437), (68440, 68447)];

pub(crate) const JAVANESE: &'static [(u32, u32)] = &[(43392, 43469), (43472, 43481), (43486, 43487)];

pub(crate) const KAITHI: &'static [(u32, u32)] = &[(69760, 69826), (69837, 69837)];

pub(crate) const KANNADA: &'static [(u32, u32)] = &[
    (3200, 3212),
    (3214, 3216),
    (3218, 3240),
    (3242, 3251),
    (3253, 3257),
    (3260, 3268),
    (3270, 3272),
    (3274, 3277),
    (3285, 3286),
    (3292, 3294),
    (3296, 3299),
    (3302, 3311),
    (3313, 3315),
];

pub(crate) const KATAKANA: &'static [(u32, u32)] = &[
    (12449, 12538),
    (12541, 12543),
    (12784, 12799),
    (13008, 13054),
    (13056, 13143),
    (65382, 65391),
    (65393, 65437),
    (110576, 110579),
    (110581, 110587),
    (110589, 110590),
    (110592, 110592),
    (110880, 110882),
    (110933, 110933),
    (110948, 110951),
];

pub(crate) const KAWI: &'static [(u32, u32)] = &[(73472, 73488), (73490, 73530), (73534, 73562)];

pub(crate) const KAYAH_LI: &'static [(u32, u32)] = &[(43264, 43309), (43311, 43311)];

pub(crate) const KHAROSHTHI: &'static [(u32, u32)] = &[
    (68096, 68099),
    (68101, 68102),
    (68108, 68115),
    (68117, 68119),
    (68121, 68149),
    (68152, 68154),
    (68159, 68168),
    (68176, 68184),
];

pub(crate) const KHITAN_SMALL_SCRIPT: &'static [(u32, u32)] = &[(94180, 94180), (101120, 101589), (101631, 101631)];

pub(crate) const KHMER: &'static [(u32, u32)] = &[(6016, 6109), (6112, 6121), (6128, 6137), (6624, 6655)];

pub(crate) const KHOJKI: &'static [(u32, u32)] = &[(70144, 70161), (70163, 70209)];

pub(crate) const KHUDAWADI: &'static [(u32, u32)] = &[(70320, 70378), (70384, 70393)];

pub(crate) const KIRAT_RAI: &'static [(u32, u32)] = &[(93504, 93561)];

pub(crate) const LAO: &'static [(u32, u32)] = &[
    (3713, 3714),
    (3716, 3716),
    (3718, 3722),
    (3724, 3747),
    (3749, 3749),
    (3751, 3773),
    (3776, 3780),
    (3782, 3782),
    (3784, 3790),
    (3792, 3801),
    (3804, 3807),
];

pub(crate) const LATIN: &'static [(u32, u32)] = &[
    (65, 90),
    (97, 122),
    (170, 170),
    (186, 186),
    (192, 214),
    (216, 246),
    (248, 696),
    (736, 740),
    (7424, 7461),
    (7468, 7516),
    (7522, 7525),
    (7531, 7543),
    (7545, 7614),
    (7680, 7935),
    (8305, 8305),
    (8319, 8319),
    (8336, 8348),
    (8490, 8491),
    (8498, 8498),
    (8526, 8526),
    (8544, 8584),
    (11360, 11391),
    (42786, 42887),
    (42891, 42972),
    (42993, 43007),
    (43824, 43866),
    (43868, 43876),
    (43878, 43881),
    (64256, 64262),
    (65313, 65338),
    (65345, 65370),
    (67456, 67461),
    (67463, 67504),
    (67506, 67514),
    (122624, 122654),
    (122661, 122666),
];

pub(crate) const LEPCHA: &'static [(u32, u32)] = &[(7168, 7223), (7227, 7241), (7245, 7247)];

pub(crate) const LIMBU: &'static [(u32, u32)] = &[(6400, 6430), (6432, 6443), (6448, 6459), (6464, 6464), (6468, 6479)];

pub(crate) const LINEAR_A: &'static [(u32, u32)] = &[(67072, 67382), (67392, 67413), (67424, 67431)];

pub(crate) const LINEAR_B: &'static [(u32, u32)] =
    &[(65536, 65547), (65549, 65574), (65576, 65594), (65596, 65597), (65599, 65613), (65616, 65629), (65664, 65786)];

pub(crate) const LISU: &'static [(u32, u32)] = &[(42192, 42239), (73648, 73648)];

pub(crate) const LYCIAN: &'static [(u32, u32)] = &[(66176, 66204)];

pub(crate) const LYDIAN: &'static [(u32, u32)] = &[(67872, 67897), (67903, 67903)];

pub(crate) const MAHAJANI: &'static [(u32, u32)] = &[(69968, 70006)];

pub(crate) const MAKASAR: &'static [(u32, u32)] = &[(73440, 73464)];

pub(crate) const MALAYALAM: &'static [(u32, u32)] =
    &[(3328, 3340), (3342, 3344), (3346, 3396), (3398, 3400), (3402, 3407), (3412, 3427), (3430, 3455)];

pub(crate) const MANDAIC: &'static [(u32, u32)] = &[(2112, 2139), (2142, 2142)];

pub(crate) const MANICHAEAN: &'static [(u32, u32)] = &[(68288, 68326), (68331, 68342)];

pub(crate) const MARCHEN: &'static [(u32, u32)] = &[(72816, 72847), (72850, 72871), (72873, 72886)];

pub(crate) const MASARAM_GONDI: &'static [(u32, u32)] =
    &[(72960, 72966), (72968, 72969), (72971, 73014), (73018, 73018), (73020, 73021), (73023, 73031), (73040, 73049)];

pub(crate) const MEDEFAIDRIN: &'static [(u32, u32)] = &[(93760, 93850)];

pub(crate) const MEETEI_MAYEK: &'static [(u32, u32)] = &[(43744, 43766), (43968, 44013), (44016, 44025)];

pub(crate) const MENDE_KIKAKUI: &'static [(u32, u32)] = &[(124928, 125124), (125127, 125142)];

pub(crate) const MEROITIC_CURSIVE: &'static [(u32, u32)] = &[(68000, 68023), (68028, 68047), (68050, 68095)];

pub(crate) const MEROITIC_HIEROGLYPHS: &'static [(u32, u32)] = &[(67968, 67999)];

pub(crate) const MIAO: &'static [(u32, u32)] = &[(93952, 94026), (94031, 94087), (94095, 94111)];

pub(crate) const MODI: &'static [(u32, u32)] = &[(71168, 71236), (71248, 71257)];

pub(crate) const MONGOLIAN: &'static [(u32, u32)] =
    &[(6144, 6145), (6148, 6148), (6150, 6169), (6176, 6264), (6272, 6314), (71264, 71276)];

pub(crate) const MRO: &'static [(u32, u32)] = &[(92736, 92766), (92768, 92777), (92782, 92783)];

pub(crate) const MULTANI: &'static [(u32, u32)] =
    &[(70272, 70278), (70280, 70280), (70282, 70285), (70287, 70301), (70303, 70313)];

pub(crate) const MYANMAR: &'static [(u32, u32)] = &[(4096, 4255), (43488, 43518), (43616, 43647), (71376, 71395)];

pub(crate) const NABATAEAN: &'static [(u32, u32)] = &[(67712, 67742), (67751, 67759)];

pub(crate) const NAG_MUNDARI: &'static [(u32, u32)] = &[(124112, 124153)];

pub(crate) const NANDINAGARI: &'static [(u32, u32)] = &[(72096, 72103), (72106, 72151), (72154, 72164)];

pub(crate) const NEW_TAI_LUE: &'static [(u32, u32)] = &[(6528, 6571), (6576, 6601), (6608, 6618), (6622, 6623)];

pub(crate) const NEWA: &'static [(u32, u32)] = &[(70656, 70747), (70749, 70753)];

pub(crate) const NKO: &'static [(u32, u32)] = &[(1984, 2042), (2045, 2047)];

pub(crate) const NUSHU: &'static [(u32, u32)] = &[(94177, 94177), (110960, 111355)];

pub(crate) const NYIAKENG_PUACHUE_HMONG: &'static [(u32, u32)] =
    &[(123136, 123180), (123184, 123197), (123200, 123209), (123214, 123215)];

pub(crate) const OGHAM: &'static [(u32, u32)] = &[(5760, 5788)];

pub(crate) const OL_CHIKI: &'static [(u32, u32)] = &[(7248, 7295)];

pub(crate) const OL_ONAL: &'static [(u32, u32)] = &[(124368, 124410), (124415, 124415)];

pub(crate) const OLD_HUNGARIAN: &'static [(u32, u32)] = &[(68736, 68786), (68800, 68850), (68858, 68863)];

pub(crate) const OLD_ITALIC: &'static [(u32, u32)] = &[(66304, 66339), (66349, 66351)];

pub(crate) const OLD_NORTH_ARABIAN: &'static [(u32, u32)] = &[(68224, 68255)];

pub(crate) const OLD_PERMIC: &'static [(u32, u32)] = &[(66384, 66426)];

pub(crate) const OLD_PERSIAN: &'static [(u32, u32)] = &[(66464, 66499), (66504, 66517)];

pub(crate) const OLD_SOGDIAN: &'static [(u32, u32)] = &[(69376, 69415)];

pub(crate) const OLD_SOUTH_ARABIAN: &'static [(u32, u32)] = &[(68192, 68223)];

pub(crate) const OLD_TURKIC: &'static [(u32, u32)] = &[(68608, 68680)];

pub(crate) const OLD_UYGHUR: &'static [(u32, u32)] = &[(69488, 69513)];

pub(crate) const ORIYA: &'static [(u32, u32)] = &[
    (2817, 2819),
    (2821, 2828),
    (2831, 2832),
    (2835, 2856),
    (2858, 2864),
    (2866, 2867),
    (2869, 2873),
    (2876, 2884),
    (2887, 2888),
    (2891, 2893),
    (2901, 2903),
    (2908, 2909),
    (2911, 2915),
    (2918, 2935),
];

pub(crate) const OSAGE: &'static [(u32, u32)] = &[(66736, 66771), (66776, 66811)];

pub(crate) const OSMANYA: &'static [(u32, u32)] = &[(66688, 66717), (66720, 66729)];

pub(crate) const PAHAWH_HMONG: &'static [(u32, u32)] =
    &[(92928, 92997), (93008, 93017), (93019, 93025), (93027, 93047), (93053, 93071)];

pub(crate) const PALMYRENE: &'static [(u32, u32)] = &[(67680, 67711)];

pub(crate) const PAU_CIN_HAU: &'static [(u32, u32)] = &[(72384, 72440)];

pub(crate) const PHAGS_PA: &'static [(u32, u32)] = &[(43072, 43127)];

pub(crate) const PHOENICIAN: &'static [(u32, u32)] = &[(67840, 67867), (67871, 67871)];

pub(crate) const PSALTER_PAHLAVI: &'static [(u32, u32)] = &[(68480, 68497), (68505, 68508), (68521, 68527)];

pub(crate) const REJANG: &'static [(u32, u32)] = &[(43312, 43347), (43359, 43359)];

pub(crate) const RUNIC: &'static [(u32, u32)] = &[(5792, 5866), (5870, 5880)];

pub(crate) const SAMARITAN: &'static [(u32, u32)] = &[(2048, 2093), (2096, 2110)];

pub(crate) const SAURASHTRA: &'static [(u32, u32)] = &[(43136, 43205), (43214, 43225)];

pub(crate) const SHARADA: &'static [(u32, u32)] = &[(70016, 70111), (72544, 72551)];

pub(crate) const SHAVIAN: &'static [(u32, u32)] = &[(66640, 66687)];

pub(crate) const SIDDHAM: &'static [(u32, u32)] = &[(71040, 71093), (71096, 71133)];

pub(crate) const SIDETIC: &'static [(u32, u32)] = &[(67904, 67929)];

pub(crate) const SIGNWRITING: &'static [(u32, u32)] = &[(120832, 121483), (121499, 121503), (121505, 121519)];

pub(crate) const SINHALA: &'static [(u32, u32)] = &[
    (3457, 3459),
    (3461, 3478),
    (3482, 3505),
    (3507, 3515),
    (3517, 3517),
    (3520, 3526),
    (3530, 3530),
    (3535, 3540),
    (3542, 3542),
    (3544, 3551),
    (3558, 3567),
    (3570, 3572),
    (70113, 70132),
];

pub(crate) const SOGDIAN: &'static [(u32, u32)] = &[(69424, 69465)];

pub(crate) const SORA_SOMPENG: &'static [(u32, u32)] = &[(69840, 69864), (69872, 69881)];

pub(crate) const SOYOMBO: &'static [(u32, u32)] = &[(72272, 72354)];

pub(crate) const SUNDANESE: &'static [(u32, u32)] = &[(7040, 7103), (7360, 7367)];

pub(crate) const SUNUWAR: &'static [(u32, u32)] = &[(72640, 72673), (72688, 72697)];

pub(crate) const SYLOTI_NAGRI: &'static [(u32, u32)] = &[(43008, 43052)];

pub(crate) const SYRIAC: &'static [(u32, u32)] = &[(1792, 1805), (1807, 1866), (1869, 1871), (2144, 2154)];

pub(crate) const TAGALOG: &'static [(u32, u32)] = &[(5888, 5909), (5919, 5919)];

pub(crate) const TAGBANWA: &'static [(u32, u32)] = &[(5984, 5996), (5998, 6000), (6002, 6003)];

pub(crate) const TAI_LE: &'static [(u32, u32)] = &[(6480, 6509), (6512, 6516)];

pub(crate) const TAI_THAM: &'static [(u32, u32)] =
    &[(6688, 6750), (6752, 6780), (6783, 6793), (6800, 6809), (6816, 6829)];

pub(crate) const TAI_VIET: &'static [(u32, u32)] = &[(43648, 43714), (43739, 43743)];

pub(crate) const TAI_YO: &'static [(u32, u32)] = &[(124608, 124638), (124640, 124661), (124670, 124671)];

pub(crate) const TAKRI: &'static [(u32, u32)] = &[(71296, 71353), (71360, 71369)];

pub(crate) const TAMIL: &'static [(u32, u32)] = &[
    (2946, 2947),
    (2949, 2954),
    (2958, 2960),
    (2962, 2965),
    (2969, 2970),
    (2972, 2972),
    (2974, 2975),
    (2979, 2980),
    (2984, 2986),
    (2990, 3001),
    (3006, 3010),
    (3014, 3016),
    (3018, 3021),
    (3024, 3024),
    (3031, 3031),
    (3046, 3066),
    (73664, 73713),
    (73727, 73727),
];

pub(crate) const TANGSA: &'static [(u32, u32)] = &[(92784, 92862), (92864, 92873)];

pub(crate) const TANGUT: &'static [(u32, u32)] = &[(94176, 94176), (94208, 101119), (101632, 101662), (101760, 101874)];

pub(crate) const TELUGU: &'static [(u32, u32)] = &[
    (3072, 3084),
    (3086, 3088),
    (3090, 3112),
    (3114, 3129),
    (3132, 3140),
    (3142, 3144),
    (3146, 3149),
    (3157, 3158),
    (3160, 3162),
    (3164, 3165),
    (3168, 3171),
    (3174, 3183),
    (3191, 3199),
];

pub(crate) const THAANA: &'static [(u32, u32)] = &[(1920, 1969)];

pub(crate) const THAI: &'static [(u32, u32)] = &[(3585, 3642), (3648, 3675)];

pub(crate) const TIBETAN: &'static [(u32, u32)] =
    &[(3840, 3911), (3913, 3948), (3953, 3991), (3993, 4028), (4030, 4044), (4046, 4052), (4057, 4058)];

pub(crate) const TIFINAGH: &'static [(u32, u32)] = &[(11568, 11623), (11631, 11632), (11647, 11647)];

pub(crate) const TIRHUTA: &'static [(u32, u32)] = &[(70784, 70855), (70864, 70873)];

pub(crate) const TODHRI: &'static [(u32, u32)] = &[(67008, 67059)];

pub(crate) const TOLONG_SIKI: &'static [(u32, u32)] = &[(73136, 73179), (73184, 73193)];

pub(crate) const TOTO: &'static [(u32, u32)] = &[(123536, 123566)];

pub(crate) const TULU_TIGALARI: &'static [(u32, u32)] = &[
    (70528, 70537),
    (70539, 70539),
    (70542, 70542),
    (70544, 70581),
    (70583, 70592),
    (70594, 70594),
    (70597, 70597),
    (70599, 70602),
    (70604, 70613),
    (70615, 70616),
    (70625, 70626),
];

pub(crate) const UGARITIC: &'static [(u32, u32)] = &[(66432, 66461), (66463, 66463)];

pub(crate) const VAI: &'static [(u32, u32)] = &[(42240, 42539)];

pub(crate) const VITHKUQI: &'static [(u32, u32)] = &[
    (66928, 66938),
    (66940, 66954),
    (66956, 66962),
    (66964, 66965),
    (66967, 66977),
    (66979, 66993),
    (66995, 67001),
    (67003, 67004),
];

pub(crate) const WANCHO: &'static [(u32, u32)] = &[(123584, 123641), (123647, 123647)];

pub(crate) const WARANG_CITI: &'static [(u32, u32)] = &[(71840, 71922), (71935, 71935)];

pub(crate) const YEZIDI: &'static [(u32, u32)] = &[(69248, 69289), (69291, 69293), (69296, 69297)];

pub(crate) const YI: &'static [(u32, u32)] = &[(40960, 42124), (42128, 42182)];

pub(crate) const ZANABAZAR_SQUARE: &'static [(u32, u32)] = &[(72192, 72263)];
