#[derive(Debug, Copy, Clone)]
pub(crate) struct CharRange {
    pub(crate) first: char,
    pub(crate) last: char,
}

pub(crate) const ID_START: &[CharRange] = &[
    CharRange { first: 'A', last: 'Z' },                 // A .. Z
    CharRange { first: 'a', last: 'z' },                 // a .. z
    CharRange { first: '\u{aa}', last: '\u{aa}' },       // ª .. ª
    CharRange { first: '\u{b5}', last: '\u{b5}' },       // µ .. µ
    CharRange { first: '\u{ba}', last: '\u{ba}' },       // º .. º
    CharRange { first: '\u{c0}', last: '\u{d6}' },       // À .. Ö
    CharRange { first: '\u{d8}', last: '\u{f6}' },       // Ø .. ö
    CharRange { first: '\u{f8}', last: '\u{2c1}' },      // ø .. ˁ
    CharRange { first: '\u{2c6}', last: '\u{2d1}' },     // ˆ .. ˑ
    CharRange { first: '\u{2e0}', last: '\u{2e4}' },     // ˠ .. ˤ
    CharRange { first: '\u{2ec}', last: '\u{2ec}' },     // ˬ .. ˬ
    CharRange { first: '\u{2ee}', last: '\u{2ee}' },     // ˮ .. ˮ
    CharRange { first: '\u{370}', last: '\u{374}' },     // Ͱ .. ʹ
    CharRange { first: '\u{376}', last: '\u{377}' },     // Ͷ .. ͷ
    CharRange { first: '\u{37a}', last: '\u{37d}' },     // ͺ .. ͽ
    CharRange { first: '\u{37f}', last: '\u{37f}' },     // Ϳ .. Ϳ
    CharRange { first: '\u{386}', last: '\u{386}' },     // Ά .. Ά
    CharRange { first: '\u{388}', last: '\u{38a}' },     // Έ .. Ί
    CharRange { first: '\u{38c}', last: '\u{38c}' },     // Ό .. Ό
    CharRange { first: '\u{38e}', last: '\u{3a1}' },     // Ύ .. Ρ
    CharRange { first: '\u{3a3}', last: '\u{3f5}' },     // Σ .. ϵ
    CharRange { first: '\u{3f7}', last: '\u{481}' },     // Ϸ .. ҁ
    CharRange { first: '\u{48a}', last: '\u{52f}' },     // Ҋ .. ԯ
    CharRange { first: '\u{531}', last: '\u{556}' },     // Ա .. Ֆ
    CharRange { first: '\u{559}', last: '\u{559}' },     // ՙ .. ՙ
    CharRange { first: '\u{560}', last: '\u{588}' },     // ՠ .. ֈ
    CharRange { first: '\u{5d0}', last: '\u{5ea}' },     // א .. ת
    CharRange { first: '\u{5ef}', last: '\u{5f2}' },     // ׯ .. ײ
    CharRange { first: '\u{620}', last: '\u{64a}' },     // ؠ .. ي
    CharRange { first: '\u{66e}', last: '\u{66f}' },     // ٮ .. ٯ
    CharRange { first: '\u{671}', last: '\u{6d3}' },     // ٱ .. ۓ
    CharRange { first: '\u{6d5}', last: '\u{6d5}' },     // ە .. ە
    CharRange { first: '\u{6e5}', last: '\u{6e6}' },     // ۥ .. ۦ
    CharRange { first: '\u{6ee}', last: '\u{6ef}' },     // ۮ .. ۯ
    CharRange { first: '\u{6fa}', last: '\u{6fc}' },     // ۺ .. ۼ
    CharRange { first: '\u{6ff}', last: '\u{6ff}' },     // ۿ .. ۿ
    CharRange { first: '\u{710}', last: '\u{710}' },     // ܐ .. ܐ
    CharRange { first: '\u{712}', last: '\u{72f}' },     // ܒ .. ܯ
    CharRange { first: '\u{74d}', last: '\u{7a5}' },     // ݍ .. ޥ
    CharRange { first: '\u{7b1}', last: '\u{7b1}' },     // ޱ .. ޱ
    CharRange { first: '\u{7ca}', last: '\u{7ea}' },     // ߊ .. ߪ
    CharRange { first: '\u{7f4}', last: '\u{7f5}' },     // ߴ .. ߵ
    CharRange { first: '\u{7fa}', last: '\u{7fa}' },     // ߺ .. ߺ
    CharRange { first: '\u{800}', last: '\u{815}' },     // ࠀ .. ࠕ
    CharRange { first: '\u{81a}', last: '\u{81a}' },     // ࠚ .. ࠚ
    CharRange { first: '\u{824}', last: '\u{824}' },     // ࠤ .. ࠤ
    CharRange { first: '\u{828}', last: '\u{828}' },     // ࠨ .. ࠨ
    CharRange { first: '\u{840}', last: '\u{858}' },     // ࡀ .. ࡘ
    CharRange { first: '\u{860}', last: '\u{86a}' },     // ࡠ .. ࡪ
    CharRange { first: '\u{8a0}', last: '\u{8b4}' },     // ࢠ .. ࢴ
    CharRange { first: '\u{8b6}', last: '\u{8bd}' },     // ࢶ .. ࢽ
    CharRange { first: '\u{904}', last: '\u{939}' },     // ऄ .. ह
    CharRange { first: '\u{93d}', last: '\u{93d}' },     // ऽ .. ऽ
    CharRange { first: '\u{950}', last: '\u{950}' },     // ॐ .. ॐ
    CharRange { first: '\u{958}', last: '\u{961}' },     // क़ .. ॡ
    CharRange { first: '\u{971}', last: '\u{980}' },     // ॱ .. ঀ
    CharRange { first: '\u{985}', last: '\u{98c}' },     // অ .. ঌ
    CharRange { first: '\u{98f}', last: '\u{990}' },     // এ .. ঐ
    CharRange { first: '\u{993}', last: '\u{9a8}' },     // ও .. ন
    CharRange { first: '\u{9aa}', last: '\u{9b0}' },     // প .. র
    CharRange { first: '\u{9b2}', last: '\u{9b2}' },     // ল .. ল
    CharRange { first: '\u{9b6}', last: '\u{9b9}' },     // শ .. হ
    CharRange { first: '\u{9bd}', last: '\u{9bd}' },     // ঽ .. ঽ
    CharRange { first: '\u{9ce}', last: '\u{9ce}' },     // ৎ .. ৎ
    CharRange { first: '\u{9dc}', last: '\u{9dd}' },     // ড় .. ঢ়
    CharRange { first: '\u{9df}', last: '\u{9e1}' },     // য় .. ৡ
    CharRange { first: '\u{9f0}', last: '\u{9f1}' },     // ৰ .. ৱ
    CharRange { first: '\u{9fc}', last: '\u{9fc}' },     // ৼ .. ৼ
    CharRange { first: '\u{a05}', last: '\u{a0a}' },     // ਅ .. ਊ
    CharRange { first: '\u{a0f}', last: '\u{a10}' },     // ਏ .. ਐ
    CharRange { first: '\u{a13}', last: '\u{a28}' },     // ਓ .. ਨ
    CharRange { first: '\u{a2a}', last: '\u{a30}' },     // ਪ .. ਰ
    CharRange { first: '\u{a32}', last: '\u{a33}' },     // ਲ .. ਲ਼
    CharRange { first: '\u{a35}', last: '\u{a36}' },     // ਵ .. ਸ਼
    CharRange { first: '\u{a38}', last: '\u{a39}' },     // ਸ .. ਹ
    CharRange { first: '\u{a59}', last: '\u{a5c}' },     // ਖ਼ .. ੜ
    CharRange { first: '\u{a5e}', last: '\u{a5e}' },     // ਫ਼ .. ਫ਼
    CharRange { first: '\u{a72}', last: '\u{a74}' },     // ੲ .. ੴ
    CharRange { first: '\u{a85}', last: '\u{a8d}' },     // અ .. ઍ
    CharRange { first: '\u{a8f}', last: '\u{a91}' },     // એ .. ઑ
    CharRange { first: '\u{a93}', last: '\u{aa8}' },     // ઓ .. ન
    CharRange { first: '\u{aaa}', last: '\u{ab0}' },     // પ .. ર
    CharRange { first: '\u{ab2}', last: '\u{ab3}' },     // લ .. ળ
    CharRange { first: '\u{ab5}', last: '\u{ab9}' },     // વ .. હ
    CharRange { first: '\u{abd}', last: '\u{abd}' },     // ઽ .. ઽ
    CharRange { first: '\u{ad0}', last: '\u{ad0}' },     // ૐ .. ૐ
    CharRange { first: '\u{ae0}', last: '\u{ae1}' },     // ૠ .. ૡ
    CharRange { first: '\u{af9}', last: '\u{af9}' },     // ૹ .. ૹ
    CharRange { first: '\u{b05}', last: '\u{b0c}' },     // ଅ .. ଌ
    CharRange { first: '\u{b0f}', last: '\u{b10}' },     // ଏ .. ଐ
    CharRange { first: '\u{b13}', last: '\u{b28}' },     // ଓ .. ନ
    CharRange { first: '\u{b2a}', last: '\u{b30}' },     // ପ .. ର
    CharRange { first: '\u{b32}', last: '\u{b33}' },     // ଲ .. ଳ
    CharRange { first: '\u{b35}', last: '\u{b39}' },     // ଵ .. ହ
    CharRange { first: '\u{b3d}', last: '\u{b3d}' },     // ଽ .. ଽ
    CharRange { first: '\u{b5c}', last: '\u{b5d}' },     // ଡ଼ .. ଢ଼
    CharRange { first: '\u{b5f}', last: '\u{b61}' },     // ୟ .. ୡ
    CharRange { first: '\u{b71}', last: '\u{b71}' },     // ୱ .. ୱ
    CharRange { first: '\u{b83}', last: '\u{b83}' },     // ஃ .. ஃ
    CharRange { first: '\u{b85}', last: '\u{b8a}' },     // அ .. ஊ
    CharRange { first: '\u{b8e}', last: '\u{b90}' },     // எ .. ஐ
    CharRange { first: '\u{b92}', last: '\u{b95}' },     // ஒ .. க
    CharRange { first: '\u{b99}', last: '\u{b9a}' },     // ங .. ச
    CharRange { first: '\u{b9c}', last: '\u{b9c}' },     // ஜ .. ஜ
    CharRange { first: '\u{b9e}', last: '\u{b9f}' },     // ஞ .. ட
    CharRange { first: '\u{ba3}', last: '\u{ba4}' },     // ண .. த
    CharRange { first: '\u{ba8}', last: '\u{baa}' },     // ந .. ப
    CharRange { first: '\u{bae}', last: '\u{bb9}' },     // ம .. ஹ
    CharRange { first: '\u{bd0}', last: '\u{bd0}' },     // ௐ .. ௐ
    CharRange { first: '\u{c05}', last: '\u{c0c}' },     // అ .. ఌ
    CharRange { first: '\u{c0e}', last: '\u{c10}' },     // ఎ .. ఐ
    CharRange { first: '\u{c12}', last: '\u{c28}' },     // ఒ .. న
    CharRange { first: '\u{c2a}', last: '\u{c39}' },     // ప .. హ
    CharRange { first: '\u{c3d}', last: '\u{c3d}' },     // ఽ .. ఽ
    CharRange { first: '\u{c58}', last: '\u{c5a}' },     // ౘ .. ౚ
    CharRange { first: '\u{c60}', last: '\u{c61}' },     // ౠ .. ౡ
    CharRange { first: '\u{c80}', last: '\u{c80}' },     // ಀ .. ಀ
    CharRange { first: '\u{c85}', last: '\u{c8c}' },     // ಅ .. ಌ
    CharRange { first: '\u{c8e}', last: '\u{c90}' },     // ಎ .. ಐ
    CharRange { first: '\u{c92}', last: '\u{ca8}' },     // ಒ .. ನ
    CharRange { first: '\u{caa}', last: '\u{cb3}' },     // ಪ .. ಳ
    CharRange { first: '\u{cb5}', last: '\u{cb9}' },     // ವ .. ಹ
    CharRange { first: '\u{cbd}', last: '\u{cbd}' },     // ಽ .. ಽ
    CharRange { first: '\u{cde}', last: '\u{cde}' },     // ೞ .. ೞ
    CharRange { first: '\u{ce0}', last: '\u{ce1}' },     // ೠ .. ೡ
    CharRange { first: '\u{cf1}', last: '\u{cf2}' },     // ೱ .. ೲ
    CharRange { first: '\u{d05}', last: '\u{d0c}' },     // അ .. ഌ
    CharRange { first: '\u{d0e}', last: '\u{d10}' },     // എ .. ഐ
    CharRange { first: '\u{d12}', last: '\u{d3a}' },     // ഒ .. ഺ
    CharRange { first: '\u{d3d}', last: '\u{d3d}' },     // ഽ .. ഽ
    CharRange { first: '\u{d4e}', last: '\u{d4e}' },     // ൎ .. ൎ
    CharRange { first: '\u{d54}', last: '\u{d56}' },     // ൔ .. ൖ
    CharRange { first: '\u{d5f}', last: '\u{d61}' },     // ൟ .. ൡ
    CharRange { first: '\u{d7a}', last: '\u{d7f}' },     // ൺ .. ൿ
    CharRange { first: '\u{d85}', last: '\u{d96}' },     // අ .. ඖ
    CharRange { first: '\u{d9a}', last: '\u{db1}' },     // ක .. න
    CharRange { first: '\u{db3}', last: '\u{dbb}' },     // ඳ .. ර
    CharRange { first: '\u{dbd}', last: '\u{dbd}' },     // ල .. ල
    CharRange { first: '\u{dc0}', last: '\u{dc6}' },     // ව .. ෆ
    CharRange { first: '\u{e01}', last: '\u{e30}' },     // ก .. ะ
    CharRange { first: '\u{e32}', last: '\u{e33}' },     // า .. ำ
    CharRange { first: '\u{e40}', last: '\u{e46}' },     // เ .. ๆ
    CharRange { first: '\u{e81}', last: '\u{e82}' },     // ກ .. ຂ
    CharRange { first: '\u{e84}', last: '\u{e84}' },     // ຄ .. ຄ
    CharRange { first: '\u{e86}', last: '\u{e8a}' },     // ຆ .. ຊ
    CharRange { first: '\u{e8c}', last: '\u{ea3}' },     // ຌ .. ຣ
    CharRange { first: '\u{ea5}', last: '\u{ea5}' },     // ລ .. ລ
    CharRange { first: '\u{ea7}', last: '\u{eb0}' },     // ວ .. ະ
    CharRange { first: '\u{eb2}', last: '\u{eb3}' },     // າ .. ຳ
    CharRange { first: '\u{ebd}', last: '\u{ebd}' },     // ຽ .. ຽ
    CharRange { first: '\u{ec0}', last: '\u{ec4}' },     // ເ .. ໄ
    CharRange { first: '\u{ec6}', last: '\u{ec6}' },     // ໆ .. ໆ
    CharRange { first: '\u{edc}', last: '\u{edf}' },     // ໜ .. ໟ
    CharRange { first: '\u{f00}', last: '\u{f00}' },     // ༀ .. ༀ
    CharRange { first: '\u{f40}', last: '\u{f47}' },     // ཀ .. ཇ
    CharRange { first: '\u{f49}', last: '\u{f6c}' },     // ཉ .. ཬ
    CharRange { first: '\u{f88}', last: '\u{f8c}' },     // ྈ .. ྌ
    CharRange { first: '\u{1000}', last: '\u{102a}' },   // က .. ဪ
    CharRange { first: '\u{103f}', last: '\u{103f}' },   // ဿ .. ဿ
    CharRange { first: '\u{1050}', last: '\u{1055}' },   // ၐ .. ၕ
    CharRange { first: '\u{105a}', last: '\u{105d}' },   // ၚ .. ၝ
    CharRange { first: '\u{1061}', last: '\u{1061}' },   // ၡ .. ၡ
    CharRange { first: '\u{1065}', last: '\u{1066}' },   // ၥ .. ၦ
    CharRange { first: '\u{106e}', last: '\u{1070}' },   // ၮ .. ၰ
    CharRange { first: '\u{1075}', last: '\u{1081}' },   // ၵ .. ႁ
    CharRange { first: '\u{108e}', last: '\u{108e}' },   // ႎ .. ႎ
    CharRange { first: '\u{10a0}', last: '\u{10c5}' },   // Ⴀ .. Ⴥ
    CharRange { first: '\u{10c7}', last: '\u{10c7}' },   // Ⴧ .. Ⴧ
    CharRange { first: '\u{10cd}', last: '\u{10cd}' },   // Ⴭ .. Ⴭ
    CharRange { first: '\u{10d0}', last: '\u{10fa}' },   // ა .. ჺ
    CharRange { first: '\u{10fc}', last: '\u{1248}' },   // ჼ .. ቈ
    CharRange { first: '\u{124a}', last: '\u{124d}' },   // ቊ .. ቍ
    CharRange { first: '\u{1250}', last: '\u{1256}' },   // ቐ .. ቖ
    CharRange { first: '\u{1258}', last: '\u{1258}' },   // ቘ .. ቘ
    CharRange { first: '\u{125a}', last: '\u{125d}' },   // ቚ .. ቝ
    CharRange { first: '\u{1260}', last: '\u{1288}' },   // በ .. ኈ
    CharRange { first: '\u{128a}', last: '\u{128d}' },   // ኊ .. ኍ
    CharRange { first: '\u{1290}', last: '\u{12b0}' },   // ነ .. ኰ
    CharRange { first: '\u{12b2}', last: '\u{12b5}' },   // ኲ .. ኵ
    CharRange { first: '\u{12b8}', last: '\u{12be}' },   // ኸ .. ኾ
    CharRange { first: '\u{12c0}', last: '\u{12c0}' },   // ዀ .. ዀ
    CharRange { first: '\u{12c2}', last: '\u{12c5}' },   // ዂ .. ዅ
    CharRange { first: '\u{12c8}', last: '\u{12d6}' },   // ወ .. ዖ
    CharRange { first: '\u{12d8}', last: '\u{1310}' },   // ዘ .. ጐ
    CharRange { first: '\u{1312}', last: '\u{1315}' },   // ጒ .. ጕ
    CharRange { first: '\u{1318}', last: '\u{135a}' },   // ጘ .. ፚ
    CharRange { first: '\u{1380}', last: '\u{138f}' },   // ᎀ .. ᎏ
    CharRange { first: '\u{13a0}', last: '\u{13f5}' },   // Ꭰ .. Ᏽ
    CharRange { first: '\u{13f8}', last: '\u{13fd}' },   // ᏸ .. ᏽ
    CharRange { first: '\u{1401}', last: '\u{166c}' },   // ᐁ .. ᙬ
    CharRange { first: '\u{166f}', last: '\u{167f}' },   // ᙯ .. ᙿ
    CharRange { first: '\u{1681}', last: '\u{169a}' },   // ᚁ .. ᚚ
    CharRange { first: '\u{16a0}', last: '\u{16ea}' },   // ᚠ .. ᛪ
    CharRange { first: '\u{16ee}', last: '\u{16f8}' },   // ᛮ .. ᛸ
    CharRange { first: '\u{1700}', last: '\u{170c}' },   // ᜀ .. ᜌ
    CharRange { first: '\u{170e}', last: '\u{1711}' },   // ᜎ .. ᜑ
    CharRange { first: '\u{1720}', last: '\u{1731}' },   // ᜠ .. ᜱ
    CharRange { first: '\u{1740}', last: '\u{1751}' },   // ᝀ .. ᝑ
    CharRange { first: '\u{1760}', last: '\u{176c}' },   // ᝠ .. ᝬ
    CharRange { first: '\u{176e}', last: '\u{1770}' },   // ᝮ .. ᝰ
    CharRange { first: '\u{1780}', last: '\u{17b3}' },   // ក .. ឳ
    CharRange { first: '\u{17d7}', last: '\u{17d7}' },   // ៗ .. ៗ
    CharRange { first: '\u{17dc}', last: '\u{17dc}' },   // ៜ .. ៜ
    CharRange { first: '\u{1820}', last: '\u{1878}' },   // ᠠ .. ᡸ
    CharRange { first: '\u{1880}', last: '\u{18a8}' },   // ᢀ .. ᢨ
    CharRange { first: '\u{18aa}', last: '\u{18aa}' },   // ᢪ .. ᢪ
    CharRange { first: '\u{18b0}', last: '\u{18f5}' },   // ᢰ .. ᣵ
    CharRange { first: '\u{1900}', last: '\u{191e}' },   // ᤀ .. ᤞ
    CharRange { first: '\u{1950}', last: '\u{196d}' },   // ᥐ .. ᥭ
    CharRange { first: '\u{1970}', last: '\u{1974}' },   // ᥰ .. ᥴ
    CharRange { first: '\u{1980}', last: '\u{19ab}' },   // ᦀ .. ᦫ
    CharRange { first: '\u{19b0}', last: '\u{19c9}' },   // ᦰ .. ᧉ
    CharRange { first: '\u{1a00}', last: '\u{1a16}' },   // ᨀ .. ᨖ
    CharRange { first: '\u{1a20}', last: '\u{1a54}' },   // ᨠ .. ᩔ
    CharRange { first: '\u{1aa7}', last: '\u{1aa7}' },   // ᪧ .. ᪧ
    CharRange { first: '\u{1b05}', last: '\u{1b33}' },   // ᬅ .. ᬳ
    CharRange { first: '\u{1b45}', last: '\u{1b4b}' },   // ᭅ .. ᭋ
    CharRange { first: '\u{1b83}', last: '\u{1ba0}' },   // ᮃ .. ᮠ
    CharRange { first: '\u{1bae}', last: '\u{1baf}' },   // ᮮ .. ᮯ
    CharRange { first: '\u{1bba}', last: '\u{1be5}' },   // ᮺ .. ᯥ
    CharRange { first: '\u{1c00}', last: '\u{1c23}' },   // ᰀ .. ᰣ
    CharRange { first: '\u{1c4d}', last: '\u{1c4f}' },   // ᱍ .. ᱏ
    CharRange { first: '\u{1c5a}', last: '\u{1c7d}' },   // ᱚ .. ᱽ
    CharRange { first: '\u{1c80}', last: '\u{1c88}' },   // ᲀ .. ᲈ
    CharRange { first: '\u{1c90}', last: '\u{1cba}' },   // Ა .. Ჺ
    CharRange { first: '\u{1cbd}', last: '\u{1cbf}' },   // Ჽ .. Ჿ
    CharRange { first: '\u{1ce9}', last: '\u{1cec}' },   // ᳩ .. ᳬ
    CharRange { first: '\u{1cee}', last: '\u{1cf3}' },   // ᳮ .. ᳳ
    CharRange { first: '\u{1cf5}', last: '\u{1cf6}' },   // ᳵ .. ᳶ
    CharRange { first: '\u{1cfa}', last: '\u{1cfa}' },   // ᳺ .. ᳺ
    CharRange { first: '\u{1d00}', last: '\u{1dbf}' },   // ᴀ .. ᶿ
    CharRange { first: '\u{1e00}', last: '\u{1f15}' },   // Ḁ .. ἕ
    CharRange { first: '\u{1f18}', last: '\u{1f1d}' },   // Ἐ .. Ἕ
    CharRange { first: '\u{1f20}', last: '\u{1f45}' },   // ἠ .. ὅ
    CharRange { first: '\u{1f48}', last: '\u{1f4d}' },   // Ὀ .. Ὅ
    CharRange { first: '\u{1f50}', last: '\u{1f57}' },   // ὐ .. ὗ
    CharRange { first: '\u{1f59}', last: '\u{1f59}' },   // Ὑ .. Ὑ
    CharRange { first: '\u{1f5b}', last: '\u{1f5b}' },   // Ὓ .. Ὓ
    CharRange { first: '\u{1f5d}', last: '\u{1f5d}' },   // Ὕ .. Ὕ
    CharRange { first: '\u{1f5f}', last: '\u{1f7d}' },   // Ὗ .. ώ
    CharRange { first: '\u{1f80}', last: '\u{1fb4}' },   // ᾀ .. ᾴ
    CharRange { first: '\u{1fb6}', last: '\u{1fbc}' },   // ᾶ .. ᾼ
    CharRange { first: '\u{1fbe}', last: '\u{1fbe}' },   // ι .. ι
    CharRange { first: '\u{1fc2}', last: '\u{1fc4}' },   // ῂ .. ῄ
    CharRange { first: '\u{1fc6}', last: '\u{1fcc}' },   // ῆ .. ῌ
    CharRange { first: '\u{1fd0}', last: '\u{1fd3}' },   // ῐ .. ΐ
    CharRange { first: '\u{1fd6}', last: '\u{1fdb}' },   // ῖ .. Ί
    CharRange { first: '\u{1fe0}', last: '\u{1fec}' },   // ῠ .. Ῥ
    CharRange { first: '\u{1ff2}', last: '\u{1ff4}' },   // ῲ .. ῴ
    CharRange { first: '\u{1ff6}', last: '\u{1ffc}' },   // ῶ .. ῼ
    CharRange { first: '\u{2071}', last: '\u{2071}' },   // ⁱ .. ⁱ
    CharRange { first: '\u{207f}', last: '\u{207f}' },   // ⁿ .. ⁿ
    CharRange { first: '\u{2090}', last: '\u{209c}' },   // ₐ .. ₜ
    CharRange { first: '\u{2102}', last: '\u{2102}' },   // ℂ .. ℂ
    CharRange { first: '\u{2107}', last: '\u{2107}' },   // ℇ .. ℇ
    CharRange { first: '\u{210a}', last: '\u{2113}' },   // ℊ .. ℓ
    CharRange { first: '\u{2115}', last: '\u{2115}' },   // ℕ .. ℕ
    CharRange { first: '\u{2118}', last: '\u{211d}' },   // ℘ .. ℝ
    CharRange { first: '\u{2124}', last: '\u{2124}' },   // ℤ .. ℤ
    CharRange { first: '\u{2126}', last: '\u{2126}' },   // Ω .. Ω
    CharRange { first: '\u{2128}', last: '\u{2128}' },   // ℨ .. ℨ
    CharRange { first: '\u{212a}', last: '\u{2139}' },   // K .. ℹ
    CharRange { first: '\u{213c}', last: '\u{213f}' },   // ℼ .. ℿ
    CharRange { first: '\u{2145}', last: '\u{2149}' },   // ⅅ .. ⅉ
    CharRange { first: '\u{214e}', last: '\u{214e}' },   // ⅎ .. ⅎ
    CharRange { first: '\u{2160}', last: '\u{2188}' },   // Ⅰ .. ↈ
    CharRange { first: '\u{2c00}', last: '\u{2c2e}' },   // Ⰰ .. Ⱞ
    CharRange { first: '\u{2c30}', last: '\u{2c5e}' },   // ⰰ .. ⱞ
    CharRange { first: '\u{2c60}', last: '\u{2ce4}' },   // Ⱡ .. ⳤ
    CharRange { first: '\u{2ceb}', last: '\u{2cee}' },   // Ⳬ .. ⳮ
    CharRange { first: '\u{2cf2}', last: '\u{2cf3}' },   // Ⳳ .. ⳳ
    CharRange { first: '\u{2d00}', last: '\u{2d25}' },   // ⴀ .. ⴥ
    CharRange { first: '\u{2d27}', last: '\u{2d27}' },   // ⴧ .. ⴧ
    CharRange { first: '\u{2d2d}', last: '\u{2d2d}' },   // ⴭ .. ⴭ
    CharRange { first: '\u{2d30}', last: '\u{2d67}' },   // ⴰ .. ⵧ
    CharRange { first: '\u{2d6f}', last: '\u{2d6f}' },   // ⵯ .. ⵯ
    CharRange { first: '\u{2d80}', last: '\u{2d96}' },   // ⶀ .. ⶖ
    CharRange { first: '\u{2da0}', last: '\u{2da6}' },   // ⶠ .. ⶦ
    CharRange { first: '\u{2da8}', last: '\u{2dae}' },   // ⶨ .. ⶮ
    CharRange { first: '\u{2db0}', last: '\u{2db6}' },   // ⶰ .. ⶶ
    CharRange { first: '\u{2db8}', last: '\u{2dbe}' },   // ⶸ .. ⶾ
    CharRange { first: '\u{2dc0}', last: '\u{2dc6}' },   // ⷀ .. ⷆ
    CharRange { first: '\u{2dc8}', last: '\u{2dce}' },   // ⷈ .. ⷎ
    CharRange { first: '\u{2dd0}', last: '\u{2dd6}' },   // ⷐ .. ⷖ
    CharRange { first: '\u{2dd8}', last: '\u{2dde}' },   // ⷘ .. ⷞ
    CharRange { first: '\u{3005}', last: '\u{3007}' },   // 々 .. 〇
    CharRange { first: '\u{3021}', last: '\u{3029}' },   // 〡 .. 〩
    CharRange { first: '\u{3031}', last: '\u{3035}' },   // 〱 .. 〵
    CharRange { first: '\u{3038}', last: '\u{303c}' },   // 〸 .. 〼
    CharRange { first: '\u{3041}', last: '\u{3096}' },   // ぁ .. ゖ
    CharRange { first: '\u{309b}', last: '\u{309f}' },   // ゛ .. ゟ
    CharRange { first: '\u{30a1}', last: '\u{30fa}' },   // ァ .. ヺ
    CharRange { first: '\u{30fc}', last: '\u{30ff}' },   // ー .. ヿ
    CharRange { first: '\u{3105}', last: '\u{312f}' },   // ㄅ .. ㄯ
    CharRange { first: '\u{3131}', last: '\u{318e}' },   // ㄱ .. ㆎ
    CharRange { first: '\u{31a0}', last: '\u{31ba}' },   // ㆠ .. ㆺ
    CharRange { first: '\u{31f0}', last: '\u{31ff}' },   // ㇰ .. ㇿ
    CharRange { first: '\u{3400}', last: '\u{4db5}' },   // 㐀 .. 䶵
    CharRange { first: '\u{4e00}', last: '\u{9fef}' },   // 一 .. 鿯
    CharRange { first: '\u{a000}', last: '\u{a48c}' },   // ꀀ .. ꒌ
    CharRange { first: '\u{a4d0}', last: '\u{a4fd}' },   // ꓐ .. ꓽ
    CharRange { first: '\u{a500}', last: '\u{a60c}' },   // ꔀ .. ꘌ
    CharRange { first: '\u{a610}', last: '\u{a61f}' },   // ꘐ .. ꘟ
    CharRange { first: '\u{a62a}', last: '\u{a62b}' },   // ꘪ .. ꘫ
    CharRange { first: '\u{a640}', last: '\u{a66e}' },   // Ꙁ .. ꙮ
    CharRange { first: '\u{a67f}', last: '\u{a69d}' },   // ꙿ .. ꚝ
    CharRange { first: '\u{a6a0}', last: '\u{a6ef}' },   // ꚠ .. ꛯ
    CharRange { first: '\u{a717}', last: '\u{a71f}' },   // ꜗ .. ꜟ
    CharRange { first: '\u{a722}', last: '\u{a788}' },   // Ꜣ .. ꞈ
    CharRange { first: '\u{a78b}', last: '\u{a7bf}' },   // Ꞌ .. ꞿ
    CharRange { first: '\u{a7c2}', last: '\u{a7c6}' },   // Ꟃ .. Ᶎ
    CharRange { first: '\u{a7f7}', last: '\u{a801}' },   // ꟷ .. ꠁ
    CharRange { first: '\u{a803}', last: '\u{a805}' },   // ꠃ .. ꠅ
    CharRange { first: '\u{a807}', last: '\u{a80a}' },   // ꠇ .. ꠊ
    CharRange { first: '\u{a80c}', last: '\u{a822}' },   // ꠌ .. ꠢ
    CharRange { first: '\u{a840}', last: '\u{a873}' },   // ꡀ .. ꡳ
    CharRange { first: '\u{a882}', last: '\u{a8b3}' },   // ꢂ .. ꢳ
    CharRange { first: '\u{a8f2}', last: '\u{a8f7}' },   // ꣲ .. ꣷ
    CharRange { first: '\u{a8fb}', last: '\u{a8fb}' },   // ꣻ .. ꣻ
    CharRange { first: '\u{a8fd}', last: '\u{a8fe}' },   // ꣽ .. ꣾ
    CharRange { first: '\u{a90a}', last: '\u{a925}' },   // ꤊ .. ꤥ
    CharRange { first: '\u{a930}', last: '\u{a946}' },   // ꤰ .. ꥆ
    CharRange { first: '\u{a960}', last: '\u{a97c}' },   // ꥠ .. ꥼ
    CharRange { first: '\u{a984}', last: '\u{a9b2}' },   // ꦄ .. ꦲ
    CharRange { first: '\u{a9cf}', last: '\u{a9cf}' },   // ꧏ .. ꧏ
    CharRange { first: '\u{a9e0}', last: '\u{a9e4}' },   // ꧠ .. ꧤ
    CharRange { first: '\u{a9e6}', last: '\u{a9ef}' },   // ꧦ .. ꧯ
    CharRange { first: '\u{a9fa}', last: '\u{a9fe}' },   // ꧺ .. ꧾ
    CharRange { first: '\u{aa00}', last: '\u{aa28}' },   // ꨀ .. ꨨ
    CharRange { first: '\u{aa40}', last: '\u{aa42}' },   // ꩀ .. ꩂ
    CharRange { first: '\u{aa44}', last: '\u{aa4b}' },   // ꩄ .. ꩋ
    CharRange { first: '\u{aa60}', last: '\u{aa76}' },   // ꩠ .. ꩶ
    CharRange { first: '\u{aa7a}', last: '\u{aa7a}' },   // ꩺ .. ꩺ
    CharRange { first: '\u{aa7e}', last: '\u{aaaf}' },   // ꩾ .. ꪯ
    CharRange { first: '\u{aab1}', last: '\u{aab1}' },   // ꪱ .. ꪱ
    CharRange { first: '\u{aab5}', last: '\u{aab6}' },   // ꪵ .. ꪶ
    CharRange { first: '\u{aab9}', last: '\u{aabd}' },   // ꪹ .. ꪽ
    CharRange { first: '\u{aac0}', last: '\u{aac0}' },   // ꫀ .. ꫀ
    CharRange { first: '\u{aac2}', last: '\u{aac2}' },   // ꫂ .. ꫂ
    CharRange { first: '\u{aadb}', last: '\u{aadd}' },   // ꫛ .. ꫝ
    CharRange { first: '\u{aae0}', last: '\u{aaea}' },   // ꫠ .. ꫪ
    CharRange { first: '\u{aaf2}', last: '\u{aaf4}' },   // ꫲ .. ꫴ
    CharRange { first: '\u{ab01}', last: '\u{ab06}' },   // ꬁ .. ꬆ
    CharRange { first: '\u{ab09}', last: '\u{ab0e}' },   // ꬉ .. ꬎ
    CharRange { first: '\u{ab11}', last: '\u{ab16}' },   // ꬑ .. ꬖ
    CharRange { first: '\u{ab20}', last: '\u{ab26}' },   // ꬠ .. ꬦ
    CharRange { first: '\u{ab28}', last: '\u{ab2e}' },   // ꬨ .. ꬮ
    CharRange { first: '\u{ab30}', last: '\u{ab5a}' },   // ꬰ .. ꭚ
    CharRange { first: '\u{ab5c}', last: '\u{ab67}' },   // ꭜ .. ꭧ
    CharRange { first: '\u{ab70}', last: '\u{abe2}' },   // ꭰ .. ꯢ
    CharRange { first: '\u{ac00}', last: '\u{d7a3}' },   // 가 .. 힣
    CharRange { first: '\u{d7b0}', last: '\u{d7c6}' },   // ힰ .. ퟆ
    CharRange { first: '\u{d7cb}', last: '\u{d7fb}' },   // ퟋ .. ퟻ
    CharRange { first: '\u{f900}', last: '\u{fa6d}' },   // 豈 .. 舘
    CharRange { first: '\u{fa70}', last: '\u{fad9}' },   // 並 .. 龎
    CharRange { first: '\u{fb00}', last: '\u{fb06}' },   // ﬀ .. ﬆ
    CharRange { first: '\u{fb13}', last: '\u{fb17}' },   // ﬓ .. ﬗ
    CharRange { first: '\u{fb1d}', last: '\u{fb1d}' },   // יִ .. יִ
    CharRange { first: '\u{fb1f}', last: '\u{fb28}' },   // ײַ .. ﬨ
    CharRange { first: '\u{fb2a}', last: '\u{fb36}' },   // שׁ .. זּ
    CharRange { first: '\u{fb38}', last: '\u{fb3c}' },   // טּ .. לּ
    CharRange { first: '\u{fb3e}', last: '\u{fb3e}' },   // מּ .. מּ
    CharRange { first: '\u{fb40}', last: '\u{fb41}' },   // נּ .. סּ
    CharRange { first: '\u{fb43}', last: '\u{fb44}' },   // ףּ .. פּ
    CharRange { first: '\u{fb46}', last: '\u{fbb1}' },   // צּ .. ﮱ
    CharRange { first: '\u{fbd3}', last: '\u{fd3d}' },   // ﯓ .. ﴽ
    CharRange { first: '\u{fd50}', last: '\u{fd8f}' },   // ﵐ .. ﶏ
    CharRange { first: '\u{fd92}', last: '\u{fdc7}' },   // ﶒ .. ﷇ
    CharRange { first: '\u{fdf0}', last: '\u{fdfb}' },   // ﷰ .. ﷻ
    CharRange { first: '\u{fe70}', last: '\u{fe74}' },   // ﹰ .. ﹴ
    CharRange { first: '\u{fe76}', last: '\u{fefc}' },   // ﹶ .. ﻼ
    CharRange { first: '\u{ff21}', last: '\u{ff3a}' },   // Ａ .. Ｚ
    CharRange { first: '\u{ff41}', last: '\u{ff5a}' },   // ａ .. ｚ
    CharRange { first: '\u{ff66}', last: '\u{ffbe}' },   // ｦ .. ﾾ
    CharRange { first: '\u{ffc2}', last: '\u{ffc7}' },   // ￂ .. ￇ
    CharRange { first: '\u{ffca}', last: '\u{ffcf}' },   // ￊ .. ￏ
    CharRange { first: '\u{ffd2}', last: '\u{ffd7}' },   // ￒ .. ￗ
    CharRange { first: '\u{ffda}', last: '\u{ffdc}' },   // ￚ .. ￜ
    CharRange { first: '\u{10000}', last: '\u{1000b}' }, // 𐀀 .. 𐀋
    CharRange { first: '\u{1000d}', last: '\u{10026}' }, // 𐀍 .. 𐀦
    CharRange { first: '\u{10028}', last: '\u{1003a}' }, // 𐀨 .. 𐀺
    CharRange { first: '\u{1003c}', last: '\u{1003d}' }, // 𐀼 .. 𐀽
    CharRange { first: '\u{1003f}', last: '\u{1004d}' }, // 𐀿 .. 𐁍
    CharRange { first: '\u{10050}', last: '\u{1005d}' }, // 𐁐 .. 𐁝
    CharRange { first: '\u{10080}', last: '\u{100fa}' }, // 𐂀 .. 𐃺
    CharRange { first: '\u{10140}', last: '\u{10174}' }, // 𐅀 .. 𐅴
    CharRange { first: '\u{10280}', last: '\u{1029c}' }, // 𐊀 .. 𐊜
    CharRange { first: '\u{102a0}', last: '\u{102d0}' }, // 𐊠 .. 𐋐
    CharRange { first: '\u{10300}', last: '\u{1031f}' }, // 𐌀 .. 𐌟
    CharRange { first: '\u{1032d}', last: '\u{1034a}' }, // 𐌭 .. 𐍊
    CharRange { first: '\u{10350}', last: '\u{10375}' }, // 𐍐 .. 𐍵
    CharRange { first: '\u{10380}', last: '\u{1039d}' }, // 𐎀 .. 𐎝
    CharRange { first: '\u{103a0}', last: '\u{103c3}' }, // 𐎠 .. 𐏃
    CharRange { first: '\u{103c8}', last: '\u{103cf}' }, // 𐏈 .. 𐏏
    CharRange { first: '\u{103d1}', last: '\u{103d5}' }, // 𐏑 .. 𐏕
    CharRange { first: '\u{10400}', last: '\u{1049d}' }, // 𐐀 .. 𐒝
    CharRange { first: '\u{104b0}', last: '\u{104d3}' }, // 𐒰 .. 𐓓
    CharRange { first: '\u{104d8}', last: '\u{104fb}' }, // 𐓘 .. 𐓻
    CharRange { first: '\u{10500}', last: '\u{10527}' }, // 𐔀 .. 𐔧
    CharRange { first: '\u{10530}', last: '\u{10563}' }, // 𐔰 .. 𐕣
    CharRange { first: '\u{10600}', last: '\u{10736}' }, // 𐘀 .. 𐜶
    CharRange { first: '\u{10740}', last: '\u{10755}' }, // 𐝀 .. 𐝕
    CharRange { first: '\u{10760}', last: '\u{10767}' }, // 𐝠 .. 𐝧
    CharRange { first: '\u{10800}', last: '\u{10805}' }, // 𐠀 .. 𐠅
    CharRange { first: '\u{10808}', last: '\u{10808}' }, // 𐠈 .. 𐠈
    CharRange { first: '\u{1080a}', last: '\u{10835}' }, // 𐠊 .. 𐠵
    CharRange { first: '\u{10837}', last: '\u{10838}' }, // 𐠷 .. 𐠸
    CharRange { first: '\u{1083c}', last: '\u{1083c}' }, // 𐠼 .. 𐠼
    CharRange { first: '\u{1083f}', last: '\u{10855}' }, // 𐠿 .. 𐡕
    CharRange { first: '\u{10860}', last: '\u{10876}' }, // 𐡠 .. 𐡶
    CharRange { first: '\u{10880}', last: '\u{1089e}' }, // 𐢀 .. 𐢞
    CharRange { first: '\u{108e0}', last: '\u{108f2}' }, // 𐣠 .. 𐣲
    CharRange { first: '\u{108f4}', last: '\u{108f5}' }, // 𐣴 .. 𐣵
    CharRange { first: '\u{10900}', last: '\u{10915}' }, // 𐤀 .. 𐤕
    CharRange { first: '\u{10920}', last: '\u{10939}' }, // 𐤠 .. 𐤹
    CharRange { first: '\u{10980}', last: '\u{109b7}' }, // 𐦀 .. 𐦷
    CharRange { first: '\u{109be}', last: '\u{109bf}' }, // 𐦾 .. 𐦿
    CharRange { first: '\u{10a00}', last: '\u{10a00}' }, // 𐨀 .. 𐨀
    CharRange { first: '\u{10a10}', last: '\u{10a13}' }, // 𐨐 .. 𐨓
    CharRange { first: '\u{10a15}', last: '\u{10a17}' }, // 𐨕 .. 𐨗
    CharRange { first: '\u{10a19}', last: '\u{10a35}' }, // 𐨙 .. 𐨵
    CharRange { first: '\u{10a60}', last: '\u{10a7c}' }, // 𐩠 .. 𐩼
    CharRange { first: '\u{10a80}', last: '\u{10a9c}' }, // 𐪀 .. 𐪜
    CharRange { first: '\u{10ac0}', last: '\u{10ac7}' }, // 𐫀 .. 𐫇
    CharRange { first: '\u{10ac9}', last: '\u{10ae4}' }, // 𐫉 .. 𐫤
    CharRange { first: '\u{10b00}', last: '\u{10b35}' }, // 𐬀 .. 𐬵
    CharRange { first: '\u{10b40}', last: '\u{10b55}' }, // 𐭀 .. 𐭕
    CharRange { first: '\u{10b60}', last: '\u{10b72}' }, // 𐭠 .. 𐭲
    CharRange { first: '\u{10b80}', last: '\u{10b91}' }, // 𐮀 .. 𐮑
    CharRange { first: '\u{10c00}', last: '\u{10c48}' }, // 𐰀 .. 𐱈
    CharRange { first: '\u{10c80}', last: '\u{10cb2}' }, // 𐲀 .. 𐲲
    CharRange { first: '\u{10cc0}', last: '\u{10cf2}' }, // 𐳀 .. 𐳲
    CharRange { first: '\u{10d00}', last: '\u{10d23}' }, // 𐴀 .. 𐴣
    CharRange { first: '\u{10f00}', last: '\u{10f1c}' }, // 𐼀 .. 𐼜
    CharRange { first: '\u{10f27}', last: '\u{10f27}' }, // 𐼧 .. 𐼧
    CharRange { first: '\u{10f30}', last: '\u{10f45}' }, // 𐼰 .. 𐽅
    CharRange { first: '\u{10fe0}', last: '\u{10ff6}' }, // 𐿠 .. 𐿶
    CharRange { first: '\u{11003}', last: '\u{11037}' }, // 𑀃 .. 𑀷
    CharRange { first: '\u{11083}', last: '\u{110af}' }, // 𑂃 .. 𑂯
    CharRange { first: '\u{110d0}', last: '\u{110e8}' }, // 𑃐 .. 𑃨
    CharRange { first: '\u{11103}', last: '\u{11126}' }, // 𑄃 .. 𑄦
    CharRange { first: '\u{11144}', last: '\u{11144}' }, // 𑅄 .. 𑅄
    CharRange { first: '\u{11150}', last: '\u{11172}' }, // 𑅐 .. 𑅲
    CharRange { first: '\u{11176}', last: '\u{11176}' }, // 𑅶 .. 𑅶
    CharRange { first: '\u{11183}', last: '\u{111b2}' }, // 𑆃 .. 𑆲
    CharRange { first: '\u{111c1}', last: '\u{111c4}' }, // 𑇁 .. 𑇄
    CharRange { first: '\u{111da}', last: '\u{111da}' }, // 𑇚 .. 𑇚
    CharRange { first: '\u{111dc}', last: '\u{111dc}' }, // 𑇜 .. 𑇜
    CharRange { first: '\u{11200}', last: '\u{11211}' }, // 𑈀 .. 𑈑
    CharRange { first: '\u{11213}', last: '\u{1122b}' }, // 𑈓 .. 𑈫
    CharRange { first: '\u{11280}', last: '\u{11286}' }, // 𑊀 .. 𑊆
    CharRange { first: '\u{11288}', last: '\u{11288}' }, // 𑊈 .. 𑊈
    CharRange { first: '\u{1128a}', last: '\u{1128d}' }, // 𑊊 .. 𑊍
    CharRange { first: '\u{1128f}', last: '\u{1129d}' }, // 𑊏 .. 𑊝
    CharRange { first: '\u{1129f}', last: '\u{112a8}' }, // 𑊟 .. 𑊨
    CharRange { first: '\u{112b0}', last: '\u{112de}' }, // 𑊰 .. 𑋞
    CharRange { first: '\u{11305}', last: '\u{1130c}' }, // 𑌅 .. 𑌌
    CharRange { first: '\u{1130f}', last: '\u{11310}' }, // 𑌏 .. 𑌐
    CharRange { first: '\u{11313}', last: '\u{11328}' }, // 𑌓 .. 𑌨
    CharRange { first: '\u{1132a}', last: '\u{11330}' }, // 𑌪 .. 𑌰
    CharRange { first: '\u{11332}', last: '\u{11333}' }, // 𑌲 .. 𑌳
    CharRange { first: '\u{11335}', last: '\u{11339}' }, // 𑌵 .. 𑌹
    CharRange { first: '\u{1133d}', last: '\u{1133d}' }, // 𑌽 .. 𑌽
    CharRange { first: '\u{11350}', last: '\u{11350}' }, // 𑍐 .. 𑍐
    CharRange { first: '\u{1135d}', last: '\u{11361}' }, // 𑍝 .. 𑍡
    CharRange { first: '\u{11400}', last: '\u{11434}' }, // 𑐀 .. 𑐴
    CharRange { first: '\u{11447}', last: '\u{1144a}' }, // 𑑇 .. 𑑊
    CharRange { first: '\u{1145f}', last: '\u{1145f}' }, // 𑑟 .. 𑑟
    CharRange { first: '\u{11480}', last: '\u{114af}' }, // 𑒀 .. 𑒯
    CharRange { first: '\u{114c4}', last: '\u{114c5}' }, // 𑓄 .. 𑓅
    CharRange { first: '\u{114c7}', last: '\u{114c7}' }, // 𑓇 .. 𑓇
    CharRange { first: '\u{11580}', last: '\u{115ae}' }, // 𑖀 .. 𑖮
    CharRange { first: '\u{115d8}', last: '\u{115db}' }, // 𑗘 .. 𑗛
    CharRange { first: '\u{11600}', last: '\u{1162f}' }, // 𑘀 .. 𑘯
    CharRange { first: '\u{11644}', last: '\u{11644}' }, // 𑙄 .. 𑙄
    CharRange { first: '\u{11680}', last: '\u{116aa}' }, // 𑚀 .. 𑚪
    CharRange { first: '\u{116b8}', last: '\u{116b8}' }, // 𑚸 .. 𑚸
    CharRange { first: '\u{11700}', last: '\u{1171a}' }, // 𑜀 .. 𑜚
    CharRange { first: '\u{11800}', last: '\u{1182b}' }, // 𑠀 .. 𑠫
    CharRange { first: '\u{118a0}', last: '\u{118df}' }, // 𑢠 .. 𑣟
    CharRange { first: '\u{118ff}', last: '\u{118ff}' }, // 𑣿 .. 𑣿
    CharRange { first: '\u{119a0}', last: '\u{119a7}' }, // 𑦠 .. 𑦧
    CharRange { first: '\u{119aa}', last: '\u{119d0}' }, // 𑦪 .. 𑧐
    CharRange { first: '\u{119e1}', last: '\u{119e1}' }, // 𑧡 .. 𑧡
    CharRange { first: '\u{119e3}', last: '\u{119e3}' }, // 𑧣 .. 𑧣
    CharRange { first: '\u{11a00}', last: '\u{11a00}' }, // 𑨀 .. 𑨀
    CharRange { first: '\u{11a0b}', last: '\u{11a32}' }, // 𑨋 .. 𑨲
    CharRange { first: '\u{11a3a}', last: '\u{11a3a}' }, // 𑨺 .. 𑨺
    CharRange { first: '\u{11a50}', last: '\u{11a50}' }, // 𑩐 .. 𑩐
    CharRange { first: '\u{11a5c}', last: '\u{11a89}' }, // 𑩜 .. 𑪉
    CharRange { first: '\u{11a9d}', last: '\u{11a9d}' }, // 𑪝 .. 𑪝
    CharRange { first: '\u{11ac0}', last: '\u{11af8}' }, // 𑫀 .. 𑫸
    CharRange { first: '\u{11c00}', last: '\u{11c08}' }, // 𑰀 .. 𑰈
    CharRange { first: '\u{11c0a}', last: '\u{11c2e}' }, // 𑰊 .. 𑰮
    CharRange { first: '\u{11c40}', last: '\u{11c40}' }, // 𑱀 .. 𑱀
    CharRange { first: '\u{11c72}', last: '\u{11c8f}' }, // 𑱲 .. 𑲏
    CharRange { first: '\u{11d00}', last: '\u{11d06}' }, // 𑴀 .. 𑴆
    CharRange { first: '\u{11d08}', last: '\u{11d09}' }, // 𑴈 .. 𑴉
    CharRange { first: '\u{11d0b}', last: '\u{11d30}' }, // 𑴋 .. 𑴰
    CharRange { first: '\u{11d46}', last: '\u{11d46}' }, // 𑵆 .. 𑵆
    CharRange { first: '\u{11d60}', last: '\u{11d65}' }, // 𑵠 .. 𑵥
    CharRange { first: '\u{11d67}', last: '\u{11d68}' }, // 𑵧 .. 𑵨
    CharRange { first: '\u{11d6a}', last: '\u{11d89}' }, // 𑵪 .. 𑶉
    CharRange { first: '\u{11d98}', last: '\u{11d98}' }, // 𑶘 .. 𑶘
    CharRange { first: '\u{11ee0}', last: '\u{11ef2}' }, // 𑻠 .. 𑻲
    CharRange { first: '\u{12000}', last: '\u{12399}' }, // 𒀀 .. 𒎙
    CharRange { first: '\u{12400}', last: '\u{1246e}' }, // 𒐀 .. 𒑮
    CharRange { first: '\u{12480}', last: '\u{12543}' }, // 𒒀 .. 𒕃
    CharRange { first: '\u{13000}', last: '\u{1342e}' }, // 𓀀 .. 𓐮
    CharRange { first: '\u{14400}', last: '\u{14646}' }, // 𔐀 .. 𔙆
    CharRange { first: '\u{16800}', last: '\u{16a38}' }, // 𖠀 .. 𖨸
    CharRange { first: '\u{16a40}', last: '\u{16a5e}' }, // 𖩀 .. 𖩞
    CharRange { first: '\u{16ad0}', last: '\u{16aed}' }, // 𖫐 .. 𖫭
    CharRange { first: '\u{16b00}', last: '\u{16b2f}' }, // 𖬀 .. 𖬯
    CharRange { first: '\u{16b40}', last: '\u{16b43}' }, // 𖭀 .. 𖭃
    CharRange { first: '\u{16b63}', last: '\u{16b77}' }, // 𖭣 .. 𖭷
    CharRange { first: '\u{16b7d}', last: '\u{16b8f}' }, // 𖭽 .. 𖮏
    CharRange { first: '\u{16e40}', last: '\u{16e7f}' }, // 𖹀 .. 𖹿
    CharRange { first: '\u{16f00}', last: '\u{16f4a}' }, // 𖼀 .. 𖽊
    CharRange { first: '\u{16f50}', last: '\u{16f50}' }, // 𖽐 .. 𖽐
    CharRange { first: '\u{16f93}', last: '\u{16f9f}' }, // 𖾓 .. 𖾟
    CharRange { first: '\u{16fe0}', last: '\u{16fe1}' }, // 𖿠 .. 𖿡
    CharRange { first: '\u{16fe3}', last: '\u{16fe3}' }, // 𖿣 .. 𖿣
    CharRange { first: '\u{17000}', last: '\u{187f7}' }, // 𗀀 .. 𘟷
    CharRange { first: '\u{18800}', last: '\u{18af2}' }, // 𘠀 .. 𘫲
    CharRange { first: '\u{1b000}', last: '\u{1b11e}' }, // 𛀀 .. 𛄞
    CharRange { first: '\u{1b150}', last: '\u{1b152}' }, // 𛅐 .. 𛅒
    CharRange { first: '\u{1b164}', last: '\u{1b167}' }, // 𛅤 .. 𛅧
    CharRange { first: '\u{1b170}', last: '\u{1b2fb}' }, // 𛅰 .. 𛋻
    CharRange { first: '\u{1bc00}', last: '\u{1bc6a}' }, // 𛰀 .. 𛱪
    CharRange { first: '\u{1bc70}', last: '\u{1bc7c}' }, // 𛱰 .. 𛱼
    CharRange { first: '\u{1bc80}', last: '\u{1bc88}' }, // 𛲀 .. 𛲈
    CharRange { first: '\u{1bc90}', last: '\u{1bc99}' }, // 𛲐 .. 𛲙
    CharRange { first: '\u{1d400}', last: '\u{1d454}' }, // 𝐀 .. 𝑔
    CharRange { first: '\u{1d456}', last: '\u{1d49c}' }, // 𝑖 .. 𝒜
    CharRange { first: '\u{1d49e}', last: '\u{1d49f}' }, // 𝒞 .. 𝒟
    CharRange { first: '\u{1d4a2}', last: '\u{1d4a2}' }, // 𝒢 .. 𝒢
    CharRange { first: '\u{1d4a5}', last: '\u{1d4a6}' }, // 𝒥 .. 𝒦
    CharRange { first: '\u{1d4a9}', last: '\u{1d4ac}' }, // 𝒩 .. 𝒬
    CharRange { first: '\u{1d4ae}', last: '\u{1d4b9}' }, // 𝒮 .. 𝒹
    CharRange { first: '\u{1d4bb}', last: '\u{1d4bb}' }, // 𝒻 .. 𝒻
    CharRange { first: '\u{1d4bd}', last: '\u{1d4c3}' }, // 𝒽 .. 𝓃
    CharRange { first: '\u{1d4c5}', last: '\u{1d505}' }, // 𝓅 .. 𝔅
    CharRange { first: '\u{1d507}', last: '\u{1d50a}' }, // 𝔇 .. 𝔊
    CharRange { first: '\u{1d50d}', last: '\u{1d514}' }, // 𝔍 .. 𝔔
    CharRange { first: '\u{1d516}', last: '\u{1d51c}' }, // 𝔖 .. 𝔜
    CharRange { first: '\u{1d51e}', last: '\u{1d539}' }, // 𝔞 .. 𝔹
    CharRange { first: '\u{1d53b}', last: '\u{1d53e}' }, // 𝔻 .. 𝔾
    CharRange { first: '\u{1d540}', last: '\u{1d544}' }, // 𝕀 .. 𝕄
    CharRange { first: '\u{1d546}', last: '\u{1d546}' }, // 𝕆 .. 𝕆
    CharRange { first: '\u{1d54a}', last: '\u{1d550}' }, // 𝕊 .. 𝕐
    CharRange { first: '\u{1d552}', last: '\u{1d6a5}' }, // 𝕒 .. 𝚥
    CharRange { first: '\u{1d6a8}', last: '\u{1d6c0}' }, // 𝚨 .. 𝛀
    CharRange { first: '\u{1d6c2}', last: '\u{1d6da}' }, // 𝛂 .. 𝛚
    CharRange { first: '\u{1d6dc}', last: '\u{1d6fa}' }, // 𝛜 .. 𝛺
    CharRange { first: '\u{1d6fc}', last: '\u{1d714}' }, // 𝛼 .. 𝜔
    CharRange { first: '\u{1d716}', last: '\u{1d734}' }, // 𝜖 .. 𝜴
    CharRange { first: '\u{1d736}', last: '\u{1d74e}' }, // 𝜶 .. 𝝎
    CharRange { first: '\u{1d750}', last: '\u{1d76e}' }, // 𝝐 .. 𝝮
    CharRange { first: '\u{1d770}', last: '\u{1d788}' }, // 𝝰 .. 𝞈
    CharRange { first: '\u{1d78a}', last: '\u{1d7a8}' }, // 𝞊 .. 𝞨
    CharRange { first: '\u{1d7aa}', last: '\u{1d7c2}' }, // 𝞪 .. 𝟂
    CharRange { first: '\u{1d7c4}', last: '\u{1d7cb}' }, // 𝟄 .. 𝟋
    CharRange { first: '\u{1e100}', last: '\u{1e12c}' }, // 𞄀 .. 𞄬
    CharRange { first: '\u{1e137}', last: '\u{1e13d}' }, // 𞄷 .. 𞄽
    CharRange { first: '\u{1e14e}', last: '\u{1e14e}' }, // 𞅎 .. 𞅎
    CharRange { first: '\u{1e2c0}', last: '\u{1e2eb}' }, // 𞋀 .. 𞋫
    CharRange { first: '\u{1e800}', last: '\u{1e8c4}' }, // 𞠀 .. 𞣄
    CharRange { first: '\u{1e900}', last: '\u{1e943}' }, // 𞤀 .. 𞥃
    CharRange { first: '\u{1e94b}', last: '\u{1e94b}' }, // 𞥋 .. 𞥋
    CharRange { first: '\u{1ee00}', last: '\u{1ee03}' }, // 𞸀 .. 𞸃
    CharRange { first: '\u{1ee05}', last: '\u{1ee1f}' }, // 𞸅 .. 𞸟
    CharRange { first: '\u{1ee21}', last: '\u{1ee22}' }, // 𞸡 .. 𞸢
    CharRange { first: '\u{1ee24}', last: '\u{1ee24}' }, // 𞸤 .. 𞸤
    CharRange { first: '\u{1ee27}', last: '\u{1ee27}' }, // 𞸧 .. 𞸧
    CharRange { first: '\u{1ee29}', last: '\u{1ee32}' }, // 𞸩 .. 𞸲
    CharRange { first: '\u{1ee34}', last: '\u{1ee37}' }, // 𞸴 .. 𞸷
    CharRange { first: '\u{1ee39}', last: '\u{1ee39}' }, // 𞸹 .. 𞸹
    CharRange { first: '\u{1ee3b}', last: '\u{1ee3b}' }, // 𞸻 .. 𞸻
    CharRange { first: '\u{1ee42}', last: '\u{1ee42}' }, // 𞹂 .. 𞹂
    CharRange { first: '\u{1ee47}', last: '\u{1ee47}' }, // 𞹇 .. 𞹇
    CharRange { first: '\u{1ee49}', last: '\u{1ee49}' }, // 𞹉 .. 𞹉
    CharRange { first: '\u{1ee4b}', last: '\u{1ee4b}' }, // 𞹋 .. 𞹋
    CharRange { first: '\u{1ee4d}', last: '\u{1ee4f}' }, // 𞹍 .. 𞹏
    CharRange { first: '\u{1ee51}', last: '\u{1ee52}' }, // 𞹑 .. 𞹒
    CharRange { first: '\u{1ee54}', last: '\u{1ee54}' }, // 𞹔 .. 𞹔
    CharRange { first: '\u{1ee57}', last: '\u{1ee57}' }, // 𞹗 .. 𞹗
    CharRange { first: '\u{1ee59}', last: '\u{1ee59}' }, // 𞹙 .. 𞹙
    CharRange { first: '\u{1ee5b}', last: '\u{1ee5b}' }, // 𞹛 .. 𞹛
    CharRange { first: '\u{1ee5d}', last: '\u{1ee5d}' }, // 𞹝 .. 𞹝
    CharRange { first: '\u{1ee5f}', last: '\u{1ee5f}' }, // 𞹟 .. 𞹟
    CharRange { first: '\u{1ee61}', last: '\u{1ee62}' }, // 𞹡 .. 𞹢
    CharRange { first: '\u{1ee64}', last: '\u{1ee64}' }, // 𞹤 .. 𞹤
    CharRange { first: '\u{1ee67}', last: '\u{1ee6a}' }, // 𞹧 .. 𞹪
    CharRange { first: '\u{1ee6c}', last: '\u{1ee72}' }, // 𞹬 .. 𞹲
    CharRange { first: '\u{1ee74}', last: '\u{1ee77}' }, // 𞹴 .. 𞹷
    CharRange { first: '\u{1ee79}', last: '\u{1ee7c}' }, // 𞹹 .. 𞹼
    CharRange { first: '\u{1ee7e}', last: '\u{1ee7e}' }, // 𞹾 .. 𞹾
    CharRange { first: '\u{1ee80}', last: '\u{1ee89}' }, // 𞺀 .. 𞺉
    CharRange { first: '\u{1ee8b}', last: '\u{1ee9b}' }, // 𞺋 .. 𞺛
    CharRange { first: '\u{1eea1}', last: '\u{1eea3}' }, // 𞺡 .. 𞺣
    CharRange { first: '\u{1eea5}', last: '\u{1eea9}' }, // 𞺥 .. 𞺩
    CharRange { first: '\u{1eeab}', last: '\u{1eebb}' }, // 𞺫 .. 𞺻
    CharRange { first: '\u{20000}', last: '\u{2a6d6}' }, // 𠀀 .. 𪛖
    CharRange { first: '\u{2a700}', last: '\u{2b734}' }, // 𪜀 .. 𫜴
    CharRange { first: '\u{2b740}', last: '\u{2b81d}' }, // 𫝀 .. 𫠝
    CharRange { first: '\u{2b820}', last: '\u{2cea1}' }, // 𫠠 .. 𬺡
    CharRange { first: '\u{2ceb0}', last: '\u{2ebe0}' }, // 𬺰 .. 𮯠
    CharRange { first: '\u{2f800}', last: '\u{2fa1d}' }, // 丽 .. 𪘀
];

pub(crate) const ID_CONTINUE: &[CharRange] = &[
    CharRange { first: '0', last: '9' },                 // 0 .. 9
    CharRange { first: 'A', last: 'Z' },                 // A .. Z
    CharRange { first: '_', last: '_' },                 // _ .. _
    CharRange { first: 'a', last: 'z' },                 // a .. z
    CharRange { first: '\u{aa}', last: '\u{aa}' },       // ª .. ª
    CharRange { first: '\u{b5}', last: '\u{b5}' },       // µ .. µ
    CharRange { first: '\u{b7}', last: '\u{b7}' },       // · .. ·
    CharRange { first: '\u{ba}', last: '\u{ba}' },       // º .. º
    CharRange { first: '\u{c0}', last: '\u{d6}' },       // À .. Ö
    CharRange { first: '\u{d8}', last: '\u{f6}' },       // Ø .. ö
    CharRange { first: '\u{f8}', last: '\u{2c1}' },      // ø .. ˁ
    CharRange { first: '\u{2c6}', last: '\u{2d1}' },     // ˆ .. ˑ
    CharRange { first: '\u{2e0}', last: '\u{2e4}' },     // ˠ .. ˤ
    CharRange { first: '\u{2ec}', last: '\u{2ec}' },     // ˬ .. ˬ
    CharRange { first: '\u{2ee}', last: '\u{2ee}' },     // ˮ .. ˮ
    CharRange { first: '\u{300}', last: '\u{374}' },     // ̀ .. ʹ
    CharRange { first: '\u{376}', last: '\u{377}' },     // Ͷ .. ͷ
    CharRange { first: '\u{37a}', last: '\u{37d}' },     // ͺ .. ͽ
    CharRange { first: '\u{37f}', last: '\u{37f}' },     // Ϳ .. Ϳ
    CharRange { first: '\u{386}', last: '\u{38a}' },     // Ά .. Ί
    CharRange { first: '\u{38c}', last: '\u{38c}' },     // Ό .. Ό
    CharRange { first: '\u{38e}', last: '\u{3a1}' },     // Ύ .. Ρ
    CharRange { first: '\u{3a3}', last: '\u{3f5}' },     // Σ .. ϵ
    CharRange { first: '\u{3f7}', last: '\u{481}' },     // Ϸ .. ҁ
    CharRange { first: '\u{483}', last: '\u{487}' },     // ҃ .. ҇
    CharRange { first: '\u{48a}', last: '\u{52f}' },     // Ҋ .. ԯ
    CharRange { first: '\u{531}', last: '\u{556}' },     // Ա .. Ֆ
    CharRange { first: '\u{559}', last: '\u{559}' },     // ՙ .. ՙ
    CharRange { first: '\u{560}', last: '\u{588}' },     // ՠ .. ֈ
    CharRange { first: '\u{591}', last: '\u{5bd}' },     // ֑ .. ֽ
    CharRange { first: '\u{5bf}', last: '\u{5bf}' },     // ֿ .. ֿ
    CharRange { first: '\u{5c1}', last: '\u{5c2}' },     // ׁ .. ׂ
    CharRange { first: '\u{5c4}', last: '\u{5c5}' },     // ׄ .. ׅ
    CharRange { first: '\u{5c7}', last: '\u{5c7}' },     // ׇ .. ׇ
    CharRange { first: '\u{5d0}', last: '\u{5ea}' },     // א .. ת
    CharRange { first: '\u{5ef}', last: '\u{5f2}' },     // ׯ .. ײ
    CharRange { first: '\u{610}', last: '\u{61a}' },     // ؐ .. ؚ
    CharRange { first: '\u{620}', last: '\u{669}' },     // ؠ .. ٩
    CharRange { first: '\u{66e}', last: '\u{6d3}' },     // ٮ .. ۓ
    CharRange { first: '\u{6d5}', last: '\u{6dc}' },     // ە .. ۜ
    CharRange { first: '\u{6df}', last: '\u{6e8}' },     // ۟ .. ۨ
    CharRange { first: '\u{6ea}', last: '\u{6fc}' },     // ۪ .. ۼ
    CharRange { first: '\u{6ff}', last: '\u{6ff}' },     // ۿ .. ۿ
    CharRange { first: '\u{710}', last: '\u{74a}' },     // ܐ .. ݊
    CharRange { first: '\u{74d}', last: '\u{7b1}' },     // ݍ .. ޱ
    CharRange { first: '\u{7c0}', last: '\u{7f5}' },     // ߀ .. ߵ
    CharRange { first: '\u{7fa}', last: '\u{7fa}' },     // ߺ .. ߺ
    CharRange { first: '\u{7fd}', last: '\u{7fd}' },     // ߽ .. ߽
    CharRange { first: '\u{800}', last: '\u{82d}' },     // ࠀ .. ࠭
    CharRange { first: '\u{840}', last: '\u{85b}' },     // ࡀ .. ࡛
    CharRange { first: '\u{860}', last: '\u{86a}' },     // ࡠ .. ࡪ
    CharRange { first: '\u{8a0}', last: '\u{8b4}' },     // ࢠ .. ࢴ
    CharRange { first: '\u{8b6}', last: '\u{8bd}' },     // ࢶ .. ࢽ
    CharRange { first: '\u{8d3}', last: '\u{8e1}' },     // ࣓ .. ࣡
    CharRange { first: '\u{8e3}', last: '\u{963}' },     // ࣣ .. ॣ
    CharRange { first: '\u{966}', last: '\u{96f}' },     // ० .. ९
    CharRange { first: '\u{971}', last: '\u{983}' },     // ॱ .. ঃ
    CharRange { first: '\u{985}', last: '\u{98c}' },     // অ .. ঌ
    CharRange { first: '\u{98f}', last: '\u{990}' },     // এ .. ঐ
    CharRange { first: '\u{993}', last: '\u{9a8}' },     // ও .. ন
    CharRange { first: '\u{9aa}', last: '\u{9b0}' },     // প .. র
    CharRange { first: '\u{9b2}', last: '\u{9b2}' },     // ল .. ল
    CharRange { first: '\u{9b6}', last: '\u{9b9}' },     // শ .. হ
    CharRange { first: '\u{9bc}', last: '\u{9c4}' },     // ় .. ৄ
    CharRange { first: '\u{9c7}', last: '\u{9c8}' },     // ে .. ৈ
    CharRange { first: '\u{9cb}', last: '\u{9ce}' },     // ো .. ৎ
    CharRange { first: '\u{9d7}', last: '\u{9d7}' },     // ৗ .. ৗ
    CharRange { first: '\u{9dc}', last: '\u{9dd}' },     // ড় .. ঢ়
    CharRange { first: '\u{9df}', last: '\u{9e3}' },     // য় .. ৣ
    CharRange { first: '\u{9e6}', last: '\u{9f1}' },     // ০ .. ৱ
    CharRange { first: '\u{9fc}', last: '\u{9fc}' },     // ৼ .. ৼ
    CharRange { first: '\u{9fe}', last: '\u{9fe}' },     // ৾ .. ৾
    CharRange { first: '\u{a01}', last: '\u{a03}' },     // ਁ .. ਃ
    CharRange { first: '\u{a05}', last: '\u{a0a}' },     // ਅ .. ਊ
    CharRange { first: '\u{a0f}', last: '\u{a10}' },     // ਏ .. ਐ
    CharRange { first: '\u{a13}', last: '\u{a28}' },     // ਓ .. ਨ
    CharRange { first: '\u{a2a}', last: '\u{a30}' },     // ਪ .. ਰ
    CharRange { first: '\u{a32}', last: '\u{a33}' },     // ਲ .. ਲ਼
    CharRange { first: '\u{a35}', last: '\u{a36}' },     // ਵ .. ਸ਼
    CharRange { first: '\u{a38}', last: '\u{a39}' },     // ਸ .. ਹ
    CharRange { first: '\u{a3c}', last: '\u{a3c}' },     // ਼ .. ਼
    CharRange { first: '\u{a3e}', last: '\u{a42}' },     // ਾ .. ੂ
    CharRange { first: '\u{a47}', last: '\u{a48}' },     // ੇ .. ੈ
    CharRange { first: '\u{a4b}', last: '\u{a4d}' },     // ੋ .. ੍
    CharRange { first: '\u{a51}', last: '\u{a51}' },     // ੑ .. ੑ
    CharRange { first: '\u{a59}', last: '\u{a5c}' },     // ਖ਼ .. ੜ
    CharRange { first: '\u{a5e}', last: '\u{a5e}' },     // ਫ਼ .. ਫ਼
    CharRange { first: '\u{a66}', last: '\u{a75}' },     // ੦ .. ੵ
    CharRange { first: '\u{a81}', last: '\u{a83}' },     // ઁ .. ઃ
    CharRange { first: '\u{a85}', last: '\u{a8d}' },     // અ .. ઍ
    CharRange { first: '\u{a8f}', last: '\u{a91}' },     // એ .. ઑ
    CharRange { first: '\u{a93}', last: '\u{aa8}' },     // ઓ .. ન
    CharRange { first: '\u{aaa}', last: '\u{ab0}' },     // પ .. ર
    CharRange { first: '\u{ab2}', last: '\u{ab3}' },     // લ .. ળ
    CharRange { first: '\u{ab5}', last: '\u{ab9}' },     // વ .. હ
    CharRange { first: '\u{abc}', last: '\u{ac5}' },     // ઼ .. ૅ
    CharRange { first: '\u{ac7}', last: '\u{ac9}' },     // ે .. ૉ
    CharRange { first: '\u{acb}', last: '\u{acd}' },     // ો .. ્
    CharRange { first: '\u{ad0}', last: '\u{ad0}' },     // ૐ .. ૐ
    CharRange { first: '\u{ae0}', last: '\u{ae3}' },     // ૠ .. ૣ
    CharRange { first: '\u{ae6}', last: '\u{aef}' },     // ૦ .. ૯
    CharRange { first: '\u{af9}', last: '\u{aff}' },     // ૹ .. ૿
    CharRange { first: '\u{b01}', last: '\u{b03}' },     // ଁ .. ଃ
    CharRange { first: '\u{b05}', last: '\u{b0c}' },     // ଅ .. ଌ
    CharRange { first: '\u{b0f}', last: '\u{b10}' },     // ଏ .. ଐ
    CharRange { first: '\u{b13}', last: '\u{b28}' },     // ଓ .. ନ
    CharRange { first: '\u{b2a}', last: '\u{b30}' },     // ପ .. ର
    CharRange { first: '\u{b32}', last: '\u{b33}' },     // ଲ .. ଳ
    CharRange { first: '\u{b35}', last: '\u{b39}' },     // ଵ .. ହ
    CharRange { first: '\u{b3c}', last: '\u{b44}' },     // ଼ .. ୄ
    CharRange { first: '\u{b47}', last: '\u{b48}' },     // େ .. ୈ
    CharRange { first: '\u{b4b}', last: '\u{b4d}' },     // ୋ .. ୍
    CharRange { first: '\u{b56}', last: '\u{b57}' },     // ୖ .. ୗ
    CharRange { first: '\u{b5c}', last: '\u{b5d}' },     // ଡ଼ .. ଢ଼
    CharRange { first: '\u{b5f}', last: '\u{b63}' },     // ୟ .. ୣ
    CharRange { first: '\u{b66}', last: '\u{b6f}' },     // ୦ .. ୯
    CharRange { first: '\u{b71}', last: '\u{b71}' },     // ୱ .. ୱ
    CharRange { first: '\u{b82}', last: '\u{b83}' },     // ஂ .. ஃ
    CharRange { first: '\u{b85}', last: '\u{b8a}' },     // அ .. ஊ
    CharRange { first: '\u{b8e}', last: '\u{b90}' },     // எ .. ஐ
    CharRange { first: '\u{b92}', last: '\u{b95}' },     // ஒ .. க
    CharRange { first: '\u{b99}', last: '\u{b9a}' },     // ங .. ச
    CharRange { first: '\u{b9c}', last: '\u{b9c}' },     // ஜ .. ஜ
    CharRange { first: '\u{b9e}', last: '\u{b9f}' },     // ஞ .. ட
    CharRange { first: '\u{ba3}', last: '\u{ba4}' },     // ண .. த
    CharRange { first: '\u{ba8}', last: '\u{baa}' },     // ந .. ப
    CharRange { first: '\u{bae}', last: '\u{bb9}' },     // ம .. ஹ
    CharRange { first: '\u{bbe}', last: '\u{bc2}' },     // ா .. ூ
    CharRange { first: '\u{bc6}', last: '\u{bc8}' },     // ெ .. ை
    CharRange { first: '\u{bca}', last: '\u{bcd}' },     // ொ .. ்
    CharRange { first: '\u{bd0}', last: '\u{bd0}' },     // ௐ .. ௐ
    CharRange { first: '\u{bd7}', last: '\u{bd7}' },     // ௗ .. ௗ
    CharRange { first: '\u{be6}', last: '\u{bef}' },     // ௦ .. ௯
    CharRange { first: '\u{c00}', last: '\u{c0c}' },     // ఀ .. ఌ
    CharRange { first: '\u{c0e}', last: '\u{c10}' },     // ఎ .. ఐ
    CharRange { first: '\u{c12}', last: '\u{c28}' },     // ఒ .. న
    CharRange { first: '\u{c2a}', last: '\u{c39}' },     // ప .. హ
    CharRange { first: '\u{c3d}', last: '\u{c44}' },     // ఽ .. ౄ
    CharRange { first: '\u{c46}', last: '\u{c48}' },     // ె .. ై
    CharRange { first: '\u{c4a}', last: '\u{c4d}' },     // ొ .. ్
    CharRange { first: '\u{c55}', last: '\u{c56}' },     // ౕ .. ౖ
    CharRange { first: '\u{c58}', last: '\u{c5a}' },     // ౘ .. ౚ
    CharRange { first: '\u{c60}', last: '\u{c63}' },     // ౠ .. ౣ
    CharRange { first: '\u{c66}', last: '\u{c6f}' },     // ౦ .. ౯
    CharRange { first: '\u{c80}', last: '\u{c83}' },     // ಀ .. ಃ
    CharRange { first: '\u{c85}', last: '\u{c8c}' },     // ಅ .. ಌ
    CharRange { first: '\u{c8e}', last: '\u{c90}' },     // ಎ .. ಐ
    CharRange { first: '\u{c92}', last: '\u{ca8}' },     // ಒ .. ನ
    CharRange { first: '\u{caa}', last: '\u{cb3}' },     // ಪ .. ಳ
    CharRange { first: '\u{cb5}', last: '\u{cb9}' },     // ವ .. ಹ
    CharRange { first: '\u{cbc}', last: '\u{cc4}' },     // ಼ .. ೄ
    CharRange { first: '\u{cc6}', last: '\u{cc8}' },     // ೆ .. ೈ
    CharRange { first: '\u{cca}', last: '\u{ccd}' },     // ೊ .. ್
    CharRange { first: '\u{cd5}', last: '\u{cd6}' },     // ೕ .. ೖ
    CharRange { first: '\u{cde}', last: '\u{cde}' },     // ೞ .. ೞ
    CharRange { first: '\u{ce0}', last: '\u{ce3}' },     // ೠ .. ೣ
    CharRange { first: '\u{ce6}', last: '\u{cef}' },     // ೦ .. ೯
    CharRange { first: '\u{cf1}', last: '\u{cf2}' },     // ೱ .. ೲ
    CharRange { first: '\u{d00}', last: '\u{d03}' },     // ഀ .. ഃ
    CharRange { first: '\u{d05}', last: '\u{d0c}' },     // അ .. ഌ
    CharRange { first: '\u{d0e}', last: '\u{d10}' },     // എ .. ഐ
    CharRange { first: '\u{d12}', last: '\u{d44}' },     // ഒ .. ൄ
    CharRange { first: '\u{d46}', last: '\u{d48}' },     // െ .. ൈ
    CharRange { first: '\u{d4a}', last: '\u{d4e}' },     // ൊ .. ൎ
    CharRange { first: '\u{d54}', last: '\u{d57}' },     // ൔ .. ൗ
    CharRange { first: '\u{d5f}', last: '\u{d63}' },     // ൟ .. ൣ
    CharRange { first: '\u{d66}', last: '\u{d6f}' },     // ൦ .. ൯
    CharRange { first: '\u{d7a}', last: '\u{d7f}' },     // ൺ .. ൿ
    CharRange { first: '\u{d82}', last: '\u{d83}' },     // ං .. ඃ
    CharRange { first: '\u{d85}', last: '\u{d96}' },     // අ .. ඖ
    CharRange { first: '\u{d9a}', last: '\u{db1}' },     // ක .. න
    CharRange { first: '\u{db3}', last: '\u{dbb}' },     // ඳ .. ර
    CharRange { first: '\u{dbd}', last: '\u{dbd}' },     // ල .. ල
    CharRange { first: '\u{dc0}', last: '\u{dc6}' },     // ව .. ෆ
    CharRange { first: '\u{dca}', last: '\u{dca}' },     // ් .. ්
    CharRange { first: '\u{dcf}', last: '\u{dd4}' },     // ා .. ු
    CharRange { first: '\u{dd6}', last: '\u{dd6}' },     // ූ .. ූ
    CharRange { first: '\u{dd8}', last: '\u{ddf}' },     // ෘ .. ෟ
    CharRange { first: '\u{de6}', last: '\u{def}' },     // ෦ .. ෯
    CharRange { first: '\u{df2}', last: '\u{df3}' },     // ෲ .. ෳ
    CharRange { first: '\u{e01}', last: '\u{e3a}' },     // ก .. ฺ
    CharRange { first: '\u{e40}', last: '\u{e4e}' },     // เ .. ๎
    CharRange { first: '\u{e50}', last: '\u{e59}' },     // ๐ .. ๙
    CharRange { first: '\u{e81}', last: '\u{e82}' },     // ກ .. ຂ
    CharRange { first: '\u{e84}', last: '\u{e84}' },     // ຄ .. ຄ
    CharRange { first: '\u{e86}', last: '\u{e8a}' },     // ຆ .. ຊ
    CharRange { first: '\u{e8c}', last: '\u{ea3}' },     // ຌ .. ຣ
    CharRange { first: '\u{ea5}', last: '\u{ea5}' },     // ລ .. ລ
    CharRange { first: '\u{ea7}', last: '\u{ebd}' },     // ວ .. ຽ
    CharRange { first: '\u{ec0}', last: '\u{ec4}' },     // ເ .. ໄ
    CharRange { first: '\u{ec6}', last: '\u{ec6}' },     // ໆ .. ໆ
    CharRange { first: '\u{ec8}', last: '\u{ecd}' },     // ່ .. ໍ
    CharRange { first: '\u{ed0}', last: '\u{ed9}' },     // ໐ .. ໙
    CharRange { first: '\u{edc}', last: '\u{edf}' },     // ໜ .. ໟ
    CharRange { first: '\u{f00}', last: '\u{f00}' },     // ༀ .. ༀ
    CharRange { first: '\u{f18}', last: '\u{f19}' },     // ༘ .. ༙
    CharRange { first: '\u{f20}', last: '\u{f29}' },     // ༠ .. ༩
    CharRange { first: '\u{f35}', last: '\u{f35}' },     // ༵ .. ༵
    CharRange { first: '\u{f37}', last: '\u{f37}' },     // ༷ .. ༷
    CharRange { first: '\u{f39}', last: '\u{f39}' },     // ༹ .. ༹
    CharRange { first: '\u{f3e}', last: '\u{f47}' },     // ༾ .. ཇ
    CharRange { first: '\u{f49}', last: '\u{f6c}' },     // ཉ .. ཬ
    CharRange { first: '\u{f71}', last: '\u{f84}' },     // ཱ .. ྄
    CharRange { first: '\u{f86}', last: '\u{f97}' },     // ྆ .. ྗ
    CharRange { first: '\u{f99}', last: '\u{fbc}' },     // ྙ .. ྼ
    CharRange { first: '\u{fc6}', last: '\u{fc6}' },     // ࿆ .. ࿆
    CharRange { first: '\u{1000}', last: '\u{1049}' },   // က .. ၉
    CharRange { first: '\u{1050}', last: '\u{109d}' },   // ၐ .. ႝ
    CharRange { first: '\u{10a0}', last: '\u{10c5}' },   // Ⴀ .. Ⴥ
    CharRange { first: '\u{10c7}', last: '\u{10c7}' },   // Ⴧ .. Ⴧ
    CharRange { first: '\u{10cd}', last: '\u{10cd}' },   // Ⴭ .. Ⴭ
    CharRange { first: '\u{10d0}', last: '\u{10fa}' },   // ა .. ჺ
    CharRange { first: '\u{10fc}', last: '\u{1248}' },   // ჼ .. ቈ
    CharRange { first: '\u{124a}', last: '\u{124d}' },   // ቊ .. ቍ
    CharRange { first: '\u{1250}', last: '\u{1256}' },   // ቐ .. ቖ
    CharRange { first: '\u{1258}', last: '\u{1258}' },   // ቘ .. ቘ
    CharRange { first: '\u{125a}', last: '\u{125d}' },   // ቚ .. ቝ
    CharRange { first: '\u{1260}', last: '\u{1288}' },   // በ .. ኈ
    CharRange { first: '\u{128a}', last: '\u{128d}' },   // ኊ .. ኍ
    CharRange { first: '\u{1290}', last: '\u{12b0}' },   // ነ .. ኰ
    CharRange { first: '\u{12b2}', last: '\u{12b5}' },   // ኲ .. ኵ
    CharRange { first: '\u{12b8}', last: '\u{12be}' },   // ኸ .. ኾ
    CharRange { first: '\u{12c0}', last: '\u{12c0}' },   // ዀ .. ዀ
    CharRange { first: '\u{12c2}', last: '\u{12c5}' },   // ዂ .. ዅ
    CharRange { first: '\u{12c8}', last: '\u{12d6}' },   // ወ .. ዖ
    CharRange { first: '\u{12d8}', last: '\u{1310}' },   // ዘ .. ጐ
    CharRange { first: '\u{1312}', last: '\u{1315}' },   // ጒ .. ጕ
    CharRange { first: '\u{1318}', last: '\u{135a}' },   // ጘ .. ፚ
    CharRange { first: '\u{135d}', last: '\u{135f}' },   // ፝ .. ፟
    CharRange { first: '\u{1369}', last: '\u{1371}' },   // ፩ .. ፱
    CharRange { first: '\u{1380}', last: '\u{138f}' },   // ᎀ .. ᎏ
    CharRange { first: '\u{13a0}', last: '\u{13f5}' },   // Ꭰ .. Ᏽ
    CharRange { first: '\u{13f8}', last: '\u{13fd}' },   // ᏸ .. ᏽ
    CharRange { first: '\u{1401}', last: '\u{166c}' },   // ᐁ .. ᙬ
    CharRange { first: '\u{166f}', last: '\u{167f}' },   // ᙯ .. ᙿ
    CharRange { first: '\u{1681}', last: '\u{169a}' },   // ᚁ .. ᚚ
    CharRange { first: '\u{16a0}', last: '\u{16ea}' },   // ᚠ .. ᛪ
    CharRange { first: '\u{16ee}', last: '\u{16f8}' },   // ᛮ .. ᛸ
    CharRange { first: '\u{1700}', last: '\u{170c}' },   // ᜀ .. ᜌ
    CharRange { first: '\u{170e}', last: '\u{1714}' },   // ᜎ .. ᜔
    CharRange { first: '\u{1720}', last: '\u{1734}' },   // ᜠ .. ᜴
    CharRange { first: '\u{1740}', last: '\u{1753}' },   // ᝀ .. ᝓ
    CharRange { first: '\u{1760}', last: '\u{176c}' },   // ᝠ .. ᝬ
    CharRange { first: '\u{176e}', last: '\u{1770}' },   // ᝮ .. ᝰ
    CharRange { first: '\u{1772}', last: '\u{1773}' },   // ᝲ .. ᝳ
    CharRange { first: '\u{1780}', last: '\u{17d3}' },   // ក .. ៓
    CharRange { first: '\u{17d7}', last: '\u{17d7}' },   // ៗ .. ៗ
    CharRange { first: '\u{17dc}', last: '\u{17dd}' },   // ៜ .. ៝
    CharRange { first: '\u{17e0}', last: '\u{17e9}' },   // ០ .. ៩
    CharRange { first: '\u{180b}', last: '\u{180d}' },   // ᠋ .. ᠍
    CharRange { first: '\u{1810}', last: '\u{1819}' },   // ᠐ .. ᠙
    CharRange { first: '\u{1820}', last: '\u{1878}' },   // ᠠ .. ᡸ
    CharRange { first: '\u{1880}', last: '\u{18aa}' },   // ᢀ .. ᢪ
    CharRange { first: '\u{18b0}', last: '\u{18f5}' },   // ᢰ .. ᣵ
    CharRange { first: '\u{1900}', last: '\u{191e}' },   // ᤀ .. ᤞ
    CharRange { first: '\u{1920}', last: '\u{192b}' },   // ᤠ .. ᤫ
    CharRange { first: '\u{1930}', last: '\u{193b}' },   // ᤰ .. ᤻
    CharRange { first: '\u{1946}', last: '\u{196d}' },   // ᥆ .. ᥭ
    CharRange { first: '\u{1970}', last: '\u{1974}' },   // ᥰ .. ᥴ
    CharRange { first: '\u{1980}', last: '\u{19ab}' },   // ᦀ .. ᦫ
    CharRange { first: '\u{19b0}', last: '\u{19c9}' },   // ᦰ .. ᧉ
    CharRange { first: '\u{19d0}', last: '\u{19da}' },   // ᧐ .. ᧚
    CharRange { first: '\u{1a00}', last: '\u{1a1b}' },   // ᨀ .. ᨛ
    CharRange { first: '\u{1a20}', last: '\u{1a5e}' },   // ᨠ .. ᩞ
    CharRange { first: '\u{1a60}', last: '\u{1a7c}' },   // ᩠ .. ᩼
    CharRange { first: '\u{1a7f}', last: '\u{1a89}' },   // ᩿ .. ᪉
    CharRange { first: '\u{1a90}', last: '\u{1a99}' },   // ᪐ .. ᪙
    CharRange { first: '\u{1aa7}', last: '\u{1aa7}' },   // ᪧ .. ᪧ
    CharRange { first: '\u{1ab0}', last: '\u{1abd}' },   // ᪰ .. ᪽
    CharRange { first: '\u{1b00}', last: '\u{1b4b}' },   // ᬀ .. ᭋ
    CharRange { first: '\u{1b50}', last: '\u{1b59}' },   // ᭐ .. ᭙
    CharRange { first: '\u{1b6b}', last: '\u{1b73}' },   // ᭫ .. ᭳
    CharRange { first: '\u{1b80}', last: '\u{1bf3}' },   // ᮀ .. ᯳
    CharRange { first: '\u{1c00}', last: '\u{1c37}' },   // ᰀ .. ᰷
    CharRange { first: '\u{1c40}', last: '\u{1c49}' },   // ᱀ .. ᱉
    CharRange { first: '\u{1c4d}', last: '\u{1c7d}' },   // ᱍ .. ᱽ
    CharRange { first: '\u{1c80}', last: '\u{1c88}' },   // ᲀ .. ᲈ
    CharRange { first: '\u{1c90}', last: '\u{1cba}' },   // Ა .. Ჺ
    CharRange { first: '\u{1cbd}', last: '\u{1cbf}' },   // Ჽ .. Ჿ
    CharRange { first: '\u{1cd0}', last: '\u{1cd2}' },   // ᳐ .. ᳒
    CharRange { first: '\u{1cd4}', last: '\u{1cfa}' },   // ᳔ .. ᳺ
    CharRange { first: '\u{1d00}', last: '\u{1df9}' },   // ᴀ .. ᷹
    CharRange { first: '\u{1dfb}', last: '\u{1f15}' },   // ᷻ .. ἕ
    CharRange { first: '\u{1f18}', last: '\u{1f1d}' },   // Ἐ .. Ἕ
    CharRange { first: '\u{1f20}', last: '\u{1f45}' },   // ἠ .. ὅ
    CharRange { first: '\u{1f48}', last: '\u{1f4d}' },   // Ὀ .. Ὅ
    CharRange { first: '\u{1f50}', last: '\u{1f57}' },   // ὐ .. ὗ
    CharRange { first: '\u{1f59}', last: '\u{1f59}' },   // Ὑ .. Ὑ
    CharRange { first: '\u{1f5b}', last: '\u{1f5b}' },   // Ὓ .. Ὓ
    CharRange { first: '\u{1f5d}', last: '\u{1f5d}' },   // Ὕ .. Ὕ
    CharRange { first: '\u{1f5f}', last: '\u{1f7d}' },   // Ὗ .. ώ
    CharRange { first: '\u{1f80}', last: '\u{1fb4}' },   // ᾀ .. ᾴ
    CharRange { first: '\u{1fb6}', last: '\u{1fbc}' },   // ᾶ .. ᾼ
    CharRange { first: '\u{1fbe}', last: '\u{1fbe}' },   // ι .. ι
    CharRange { first: '\u{1fc2}', last: '\u{1fc4}' },   // ῂ .. ῄ
    CharRange { first: '\u{1fc6}', last: '\u{1fcc}' },   // ῆ .. ῌ
    CharRange { first: '\u{1fd0}', last: '\u{1fd3}' },   // ῐ .. ΐ
    CharRange { first: '\u{1fd6}', last: '\u{1fdb}' },   // ῖ .. Ί
    CharRange { first: '\u{1fe0}', last: '\u{1fec}' },   // ῠ .. Ῥ
    CharRange { first: '\u{1ff2}', last: '\u{1ff4}' },   // ῲ .. ῴ
    CharRange { first: '\u{1ff6}', last: '\u{1ffc}' },   // ῶ .. ῼ
    CharRange { first: '\u{203f}', last: '\u{2040}' },   // ‿ .. ⁀
    CharRange { first: '\u{2054}', last: '\u{2054}' },   // ⁔ .. ⁔
    CharRange { first: '\u{2071}', last: '\u{2071}' },   // ⁱ .. ⁱ
    CharRange { first: '\u{207f}', last: '\u{207f}' },   // ⁿ .. ⁿ
    CharRange { first: '\u{2090}', last: '\u{209c}' },   // ₐ .. ₜ
    CharRange { first: '\u{20d0}', last: '\u{20dc}' },   // ⃐ .. ⃜
    CharRange { first: '\u{20e1}', last: '\u{20e1}' },   // ⃡ .. ⃡
    CharRange { first: '\u{20e5}', last: '\u{20f0}' },   // ⃥ .. ⃰
    CharRange { first: '\u{2102}', last: '\u{2102}' },   // ℂ .. ℂ
    CharRange { first: '\u{2107}', last: '\u{2107}' },   // ℇ .. ℇ
    CharRange { first: '\u{210a}', last: '\u{2113}' },   // ℊ .. ℓ
    CharRange { first: '\u{2115}', last: '\u{2115}' },   // ℕ .. ℕ
    CharRange { first: '\u{2118}', last: '\u{211d}' },   // ℘ .. ℝ
    CharRange { first: '\u{2124}', last: '\u{2124}' },   // ℤ .. ℤ
    CharRange { first: '\u{2126}', last: '\u{2126}' },   // Ω .. Ω
    CharRange { first: '\u{2128}', last: '\u{2128}' },   // ℨ .. ℨ
    CharRange { first: '\u{212a}', last: '\u{2139}' },   // K .. ℹ
    CharRange { first: '\u{213c}', last: '\u{213f}' },   // ℼ .. ℿ
    CharRange { first: '\u{2145}', last: '\u{2149}' },   // ⅅ .. ⅉ
    CharRange { first: '\u{214e}', last: '\u{214e}' },   // ⅎ .. ⅎ
    CharRange { first: '\u{2160}', last: '\u{2188}' },   // Ⅰ .. ↈ
    CharRange { first: '\u{2c00}', last: '\u{2c2e}' },   // Ⰰ .. Ⱞ
    CharRange { first: '\u{2c30}', last: '\u{2c5e}' },   // ⰰ .. ⱞ
    CharRange { first: '\u{2c60}', last: '\u{2ce4}' },   // Ⱡ .. ⳤ
    CharRange { first: '\u{2ceb}', last: '\u{2cf3}' },   // Ⳬ .. ⳳ
    CharRange { first: '\u{2d00}', last: '\u{2d25}' },   // ⴀ .. ⴥ
    CharRange { first: '\u{2d27}', last: '\u{2d27}' },   // ⴧ .. ⴧ
    CharRange { first: '\u{2d2d}', last: '\u{2d2d}' },   // ⴭ .. ⴭ
    CharRange { first: '\u{2d30}', last: '\u{2d67}' },   // ⴰ .. ⵧ
    CharRange { first: '\u{2d6f}', last: '\u{2d6f}' },   // ⵯ .. ⵯ
    CharRange { first: '\u{2d7f}', last: '\u{2d96}' },   // ⵿ .. ⶖ
    CharRange { first: '\u{2da0}', last: '\u{2da6}' },   // ⶠ .. ⶦ
    CharRange { first: '\u{2da8}', last: '\u{2dae}' },   // ⶨ .. ⶮ
    CharRange { first: '\u{2db0}', last: '\u{2db6}' },   // ⶰ .. ⶶ
    CharRange { first: '\u{2db8}', last: '\u{2dbe}' },   // ⶸ .. ⶾ
    CharRange { first: '\u{2dc0}', last: '\u{2dc6}' },   // ⷀ .. ⷆ
    CharRange { first: '\u{2dc8}', last: '\u{2dce}' },   // ⷈ .. ⷎ
    CharRange { first: '\u{2dd0}', last: '\u{2dd6}' },   // ⷐ .. ⷖ
    CharRange { first: '\u{2dd8}', last: '\u{2dde}' },   // ⷘ .. ⷞ
    CharRange { first: '\u{2de0}', last: '\u{2dff}' },   // ⷠ .. ⷿ
    CharRange { first: '\u{3005}', last: '\u{3007}' },   // 々 .. 〇
    CharRange { first: '\u{3021}', last: '\u{302f}' },   // 〡 .. 〯
    CharRange { first: '\u{3031}', last: '\u{3035}' },   // 〱 .. 〵
    CharRange { first: '\u{3038}', last: '\u{303c}' },   // 〸 .. 〼
    CharRange { first: '\u{3041}', last: '\u{3096}' },   // ぁ .. ゖ
    CharRange { first: '\u{3099}', last: '\u{309f}' },   // ゙ .. ゟ
    CharRange { first: '\u{30a1}', last: '\u{30fa}' },   // ァ .. ヺ
    CharRange { first: '\u{30fc}', last: '\u{30ff}' },   // ー .. ヿ
    CharRange { first: '\u{3105}', last: '\u{312f}' },   // ㄅ .. ㄯ
    CharRange { first: '\u{3131}', last: '\u{318e}' },   // ㄱ .. ㆎ
    CharRange { first: '\u{31a0}', last: '\u{31ba}' },   // ㆠ .. ㆺ
    CharRange { first: '\u{31f0}', last: '\u{31ff}' },   // ㇰ .. ㇿ
    CharRange { first: '\u{3400}', last: '\u{4db5}' },   // 㐀 .. 䶵
    CharRange { first: '\u{4e00}', last: '\u{9fef}' },   // 一 .. 鿯
    CharRange { first: '\u{a000}', last: '\u{a48c}' },   // ꀀ .. ꒌ
    CharRange { first: '\u{a4d0}', last: '\u{a4fd}' },   // ꓐ .. ꓽ
    CharRange { first: '\u{a500}', last: '\u{a60c}' },   // ꔀ .. ꘌ
    CharRange { first: '\u{a610}', last: '\u{a62b}' },   // ꘐ .. ꘫ
    CharRange { first: '\u{a640}', last: '\u{a66f}' },   // Ꙁ .. ꙯
    CharRange { first: '\u{a674}', last: '\u{a67d}' },   // ꙴ .. ꙽
    CharRange { first: '\u{a67f}', last: '\u{a6f1}' },   // ꙿ .. ꛱
    CharRange { first: '\u{a717}', last: '\u{a71f}' },   // ꜗ .. ꜟ
    CharRange { first: '\u{a722}', last: '\u{a788}' },   // Ꜣ .. ꞈ
    CharRange { first: '\u{a78b}', last: '\u{a7bf}' },   // Ꞌ .. ꞿ
    CharRange { first: '\u{a7c2}', last: '\u{a7c6}' },   // Ꟃ .. Ᶎ
    CharRange { first: '\u{a7f7}', last: '\u{a827}' },   // ꟷ .. ꠧ
    CharRange { first: '\u{a840}', last: '\u{a873}' },   // ꡀ .. ꡳ
    CharRange { first: '\u{a880}', last: '\u{a8c5}' },   // ꢀ .. ꣅ
    CharRange { first: '\u{a8d0}', last: '\u{a8d9}' },   // ꣐ .. ꣙
    CharRange { first: '\u{a8e0}', last: '\u{a8f7}' },   // ꣠ .. ꣷ
    CharRange { first: '\u{a8fb}', last: '\u{a8fb}' },   // ꣻ .. ꣻ
    CharRange { first: '\u{a8fd}', last: '\u{a92d}' },   // ꣽ .. ꤭
    CharRange { first: '\u{a930}', last: '\u{a953}' },   // ꤰ .. ꥓
    CharRange { first: '\u{a960}', last: '\u{a97c}' },   // ꥠ .. ꥼ
    CharRange { first: '\u{a980}', last: '\u{a9c0}' },   // ꦀ .. ꧀
    CharRange { first: '\u{a9cf}', last: '\u{a9d9}' },   // ꧏ .. ꧙
    CharRange { first: '\u{a9e0}', last: '\u{a9fe}' },   // ꧠ .. ꧾ
    CharRange { first: '\u{aa00}', last: '\u{aa36}' },   // ꨀ .. ꨶ
    CharRange { first: '\u{aa40}', last: '\u{aa4d}' },   // ꩀ .. ꩍ
    CharRange { first: '\u{aa50}', last: '\u{aa59}' },   // ꩐ .. ꩙
    CharRange { first: '\u{aa60}', last: '\u{aa76}' },   // ꩠ .. ꩶ
    CharRange { first: '\u{aa7a}', last: '\u{aac2}' },   // ꩺ .. ꫂ
    CharRange { first: '\u{aadb}', last: '\u{aadd}' },   // ꫛ .. ꫝ
    CharRange { first: '\u{aae0}', last: '\u{aaef}' },   // ꫠ .. ꫯ
    CharRange { first: '\u{aaf2}', last: '\u{aaf6}' },   // ꫲ .. ꫶
    CharRange { first: '\u{ab01}', last: '\u{ab06}' },   // ꬁ .. ꬆ
    CharRange { first: '\u{ab09}', last: '\u{ab0e}' },   // ꬉ .. ꬎ
    CharRange { first: '\u{ab11}', last: '\u{ab16}' },   // ꬑ .. ꬖ
    CharRange { first: '\u{ab20}', last: '\u{ab26}' },   // ꬠ .. ꬦ
    CharRange { first: '\u{ab28}', last: '\u{ab2e}' },   // ꬨ .. ꬮ
    CharRange { first: '\u{ab30}', last: '\u{ab5a}' },   // ꬰ .. ꭚ
    CharRange { first: '\u{ab5c}', last: '\u{ab67}' },   // ꭜ .. ꭧ
    CharRange { first: '\u{ab70}', last: '\u{abea}' },   // ꭰ .. ꯪ
    CharRange { first: '\u{abec}', last: '\u{abed}' },   // ꯬ .. ꯭
    CharRange { first: '\u{abf0}', last: '\u{abf9}' },   // ꯰ .. ꯹
    CharRange { first: '\u{ac00}', last: '\u{d7a3}' },   // 가 .. 힣
    CharRange { first: '\u{d7b0}', last: '\u{d7c6}' },   // ힰ .. ퟆ
    CharRange { first: '\u{d7cb}', last: '\u{d7fb}' },   // ퟋ .. ퟻ
    CharRange { first: '\u{f900}', last: '\u{fa6d}' },   // 豈 .. 舘
    CharRange { first: '\u{fa70}', last: '\u{fad9}' },   // 並 .. 龎
    CharRange { first: '\u{fb00}', last: '\u{fb06}' },   // ﬀ .. ﬆ
    CharRange { first: '\u{fb13}', last: '\u{fb17}' },   // ﬓ .. ﬗ
    CharRange { first: '\u{fb1d}', last: '\u{fb28}' },   // יִ .. ﬨ
    CharRange { first: '\u{fb2a}', last: '\u{fb36}' },   // שׁ .. זּ
    CharRange { first: '\u{fb38}', last: '\u{fb3c}' },   // טּ .. לּ
    CharRange { first: '\u{fb3e}', last: '\u{fb3e}' },   // מּ .. מּ
    CharRange { first: '\u{fb40}', last: '\u{fb41}' },   // נּ .. סּ
    CharRange { first: '\u{fb43}', last: '\u{fb44}' },   // ףּ .. פּ
    CharRange { first: '\u{fb46}', last: '\u{fbb1}' },   // צּ .. ﮱ
    CharRange { first: '\u{fbd3}', last: '\u{fd3d}' },   // ﯓ .. ﴽ
    CharRange { first: '\u{fd50}', last: '\u{fd8f}' },   // ﵐ .. ﶏ
    CharRange { first: '\u{fd92}', last: '\u{fdc7}' },   // ﶒ .. ﷇ
    CharRange { first: '\u{fdf0}', last: '\u{fdfb}' },   // ﷰ .. ﷻ
    CharRange { first: '\u{fe00}', last: '\u{fe0f}' },   // ︀ .. ️
    CharRange { first: '\u{fe20}', last: '\u{fe2f}' },   // ︠ .. ︯
    CharRange { first: '\u{fe33}', last: '\u{fe34}' },   // ︳ .. ︴
    CharRange { first: '\u{fe4d}', last: '\u{fe4f}' },   // ﹍ .. ﹏
    CharRange { first: '\u{fe70}', last: '\u{fe74}' },   // ﹰ .. ﹴ
    CharRange { first: '\u{fe76}', last: '\u{fefc}' },   // ﹶ .. ﻼ
    CharRange { first: '\u{ff10}', last: '\u{ff19}' },   // ０ .. ９
    CharRange { first: '\u{ff21}', last: '\u{ff3a}' },   // Ａ .. Ｚ
    CharRange { first: '\u{ff3f}', last: '\u{ff3f}' },   // ＿ .. ＿
    CharRange { first: '\u{ff41}', last: '\u{ff5a}' },   // ａ .. ｚ
    CharRange { first: '\u{ff66}', last: '\u{ffbe}' },   // ｦ .. ﾾ
    CharRange { first: '\u{ffc2}', last: '\u{ffc7}' },   // ￂ .. ￇ
    CharRange { first: '\u{ffca}', last: '\u{ffcf}' },   // ￊ .. ￏ
    CharRange { first: '\u{ffd2}', last: '\u{ffd7}' },   // ￒ .. ￗ
    CharRange { first: '\u{ffda}', last: '\u{ffdc}' },   // ￚ .. ￜ
    CharRange { first: '\u{10000}', last: '\u{1000b}' }, // 𐀀 .. 𐀋
    CharRange { first: '\u{1000d}', last: '\u{10026}' }, // 𐀍 .. 𐀦
    CharRange { first: '\u{10028}', last: '\u{1003a}' }, // 𐀨 .. 𐀺
    CharRange { first: '\u{1003c}', last: '\u{1003d}' }, // 𐀼 .. 𐀽
    CharRange { first: '\u{1003f}', last: '\u{1004d}' }, // 𐀿 .. 𐁍
    CharRange { first: '\u{10050}', last: '\u{1005d}' }, // 𐁐 .. 𐁝
    CharRange { first: '\u{10080}', last: '\u{100fa}' }, // 𐂀 .. 𐃺
    CharRange { first: '\u{10140}', last: '\u{10174}' }, // 𐅀 .. 𐅴
    CharRange { first: '\u{101fd}', last: '\u{101fd}' }, // 𐇽 .. 𐇽
    CharRange { first: '\u{10280}', last: '\u{1029c}' }, // 𐊀 .. 𐊜
    CharRange { first: '\u{102a0}', last: '\u{102d0}' }, // 𐊠 .. 𐋐
    CharRange { first: '\u{102e0}', last: '\u{102e0}' }, // 𐋠 .. 𐋠
    CharRange { first: '\u{10300}', last: '\u{1031f}' }, // 𐌀 .. 𐌟
    CharRange { first: '\u{1032d}', last: '\u{1034a}' }, // 𐌭 .. 𐍊
    CharRange { first: '\u{10350}', last: '\u{1037a}' }, // 𐍐 .. 𐍺
    CharRange { first: '\u{10380}', last: '\u{1039d}' }, // 𐎀 .. 𐎝
    CharRange { first: '\u{103a0}', last: '\u{103c3}' }, // 𐎠 .. 𐏃
    CharRange { first: '\u{103c8}', last: '\u{103cf}' }, // 𐏈 .. 𐏏
    CharRange { first: '\u{103d1}', last: '\u{103d5}' }, // 𐏑 .. 𐏕
    CharRange { first: '\u{10400}', last: '\u{1049d}' }, // 𐐀 .. 𐒝
    CharRange { first: '\u{104a0}', last: '\u{104a9}' }, // 𐒠 .. 𐒩
    CharRange { first: '\u{104b0}', last: '\u{104d3}' }, // 𐒰 .. 𐓓
    CharRange { first: '\u{104d8}', last: '\u{104fb}' }, // 𐓘 .. 𐓻
    CharRange { first: '\u{10500}', last: '\u{10527}' }, // 𐔀 .. 𐔧
    CharRange { first: '\u{10530}', last: '\u{10563}' }, // 𐔰 .. 𐕣
    CharRange { first: '\u{10600}', last: '\u{10736}' }, // 𐘀 .. 𐜶
    CharRange { first: '\u{10740}', last: '\u{10755}' }, // 𐝀 .. 𐝕
    CharRange { first: '\u{10760}', last: '\u{10767}' }, // 𐝠 .. 𐝧
    CharRange { first: '\u{10800}', last: '\u{10805}' }, // 𐠀 .. 𐠅
    CharRange { first: '\u{10808}', last: '\u{10808}' }, // 𐠈 .. 𐠈
    CharRange { first: '\u{1080a}', last: '\u{10835}' }, // 𐠊 .. 𐠵
    CharRange { first: '\u{10837}', last: '\u{10838}' }, // 𐠷 .. 𐠸
    CharRange { first: '\u{1083c}', last: '\u{1083c}' }, // 𐠼 .. 𐠼
    CharRange { first: '\u{1083f}', last: '\u{10855}' }, // 𐠿 .. 𐡕
    CharRange { first: '\u{10860}', last: '\u{10876}' }, // 𐡠 .. 𐡶
    CharRange { first: '\u{10880}', last: '\u{1089e}' }, // 𐢀 .. 𐢞
    CharRange { first: '\u{108e0}', last: '\u{108f2}' }, // 𐣠 .. 𐣲
    CharRange { first: '\u{108f4}', last: '\u{108f5}' }, // 𐣴 .. 𐣵
    CharRange { first: '\u{10900}', last: '\u{10915}' }, // 𐤀 .. 𐤕
    CharRange { first: '\u{10920}', last: '\u{10939}' }, // 𐤠 .. 𐤹
    CharRange { first: '\u{10980}', last: '\u{109b7}' }, // 𐦀 .. 𐦷
    CharRange { first: '\u{109be}', last: '\u{109bf}' }, // 𐦾 .. 𐦿
    CharRange { first: '\u{10a00}', last: '\u{10a03}' }, // 𐨀 .. 𐨃
    CharRange { first: '\u{10a05}', last: '\u{10a06}' }, // 𐨅 .. 𐨆
    CharRange { first: '\u{10a0c}', last: '\u{10a13}' }, // 𐨌 .. 𐨓
    CharRange { first: '\u{10a15}', last: '\u{10a17}' }, // 𐨕 .. 𐨗
    CharRange { first: '\u{10a19}', last: '\u{10a35}' }, // 𐨙 .. 𐨵
    CharRange { first: '\u{10a38}', last: '\u{10a3a}' }, // 𐨸 .. 𐨺
    CharRange { first: '\u{10a3f}', last: '\u{10a3f}' }, // 𐨿 .. 𐨿
    CharRange { first: '\u{10a60}', last: '\u{10a7c}' }, // 𐩠 .. 𐩼
    CharRange { first: '\u{10a80}', last: '\u{10a9c}' }, // 𐪀 .. 𐪜
    CharRange { first: '\u{10ac0}', last: '\u{10ac7}' }, // 𐫀 .. 𐫇
    CharRange { first: '\u{10ac9}', last: '\u{10ae6}' }, // 𐫉 .. 𐫦
    CharRange { first: '\u{10b00}', last: '\u{10b35}' }, // 𐬀 .. 𐬵
    CharRange { first: '\u{10b40}', last: '\u{10b55}' }, // 𐭀 .. 𐭕
    CharRange { first: '\u{10b60}', last: '\u{10b72}' }, // 𐭠 .. 𐭲
    CharRange { first: '\u{10b80}', last: '\u{10b91}' }, // 𐮀 .. 𐮑
    CharRange { first: '\u{10c00}', last: '\u{10c48}' }, // 𐰀 .. 𐱈
    CharRange { first: '\u{10c80}', last: '\u{10cb2}' }, // 𐲀 .. 𐲲
    CharRange { first: '\u{10cc0}', last: '\u{10cf2}' }, // 𐳀 .. 𐳲
    CharRange { first: '\u{10d00}', last: '\u{10d27}' }, // 𐴀 .. 𐴧
    CharRange { first: '\u{10d30}', last: '\u{10d39}' }, // 𐴰 .. 𐴹
    CharRange { first: '\u{10f00}', last: '\u{10f1c}' }, // 𐼀 .. 𐼜
    CharRange { first: '\u{10f27}', last: '\u{10f27}' }, // 𐼧 .. 𐼧
    CharRange { first: '\u{10f30}', last: '\u{10f50}' }, // 𐼰 .. 𐽐
    CharRange { first: '\u{10fe0}', last: '\u{10ff6}' }, // 𐿠 .. 𐿶
    CharRange { first: '\u{11000}', last: '\u{11046}' }, // 𑀀 .. 𑁆
    CharRange { first: '\u{11066}', last: '\u{1106f}' }, // 𑁦 .. 𑁯
    CharRange { first: '\u{1107f}', last: '\u{110ba}' }, // 𑁿 .. 𑂺
    CharRange { first: '\u{110d0}', last: '\u{110e8}' }, // 𑃐 .. 𑃨
    CharRange { first: '\u{110f0}', last: '\u{110f9}' }, // 𑃰 .. 𑃹
    CharRange { first: '\u{11100}', last: '\u{11134}' }, // 𑄀 .. 𑄴
    CharRange { first: '\u{11136}', last: '\u{1113f}' }, // 𑄶 .. 𑄿
    CharRange { first: '\u{11144}', last: '\u{11146}' }, // 𑅄 .. 𑅆
    CharRange { first: '\u{11150}', last: '\u{11173}' }, // 𑅐 .. 𑅳
    CharRange { first: '\u{11176}', last: '\u{11176}' }, // 𑅶 .. 𑅶
    CharRange { first: '\u{11180}', last: '\u{111c4}' }, // 𑆀 .. 𑇄
    CharRange { first: '\u{111c9}', last: '\u{111cc}' }, // 𑇉 .. 𑇌
    CharRange { first: '\u{111d0}', last: '\u{111da}' }, // 𑇐 .. 𑇚
    CharRange { first: '\u{111dc}', last: '\u{111dc}' }, // 𑇜 .. 𑇜
    CharRange { first: '\u{11200}', last: '\u{11211}' }, // 𑈀 .. 𑈑
    CharRange { first: '\u{11213}', last: '\u{11237}' }, // 𑈓 .. 𑈷
    CharRange { first: '\u{1123e}', last: '\u{1123e}' }, // 𑈾 .. 𑈾
    CharRange { first: '\u{11280}', last: '\u{11286}' }, // 𑊀 .. 𑊆
    CharRange { first: '\u{11288}', last: '\u{11288}' }, // 𑊈 .. 𑊈
    CharRange { first: '\u{1128a}', last: '\u{1128d}' }, // 𑊊 .. 𑊍
    CharRange { first: '\u{1128f}', last: '\u{1129d}' }, // 𑊏 .. 𑊝
    CharRange { first: '\u{1129f}', last: '\u{112a8}' }, // 𑊟 .. 𑊨
    CharRange { first: '\u{112b0}', last: '\u{112ea}' }, // 𑊰 .. 𑋪
    CharRange { first: '\u{112f0}', last: '\u{112f9}' }, // 𑋰 .. 𑋹
    CharRange { first: '\u{11300}', last: '\u{11303}' }, // 𑌀 .. 𑌃
    CharRange { first: '\u{11305}', last: '\u{1130c}' }, // 𑌅 .. 𑌌
    CharRange { first: '\u{1130f}', last: '\u{11310}' }, // 𑌏 .. 𑌐
    CharRange { first: '\u{11313}', last: '\u{11328}' }, // 𑌓 .. 𑌨
    CharRange { first: '\u{1132a}', last: '\u{11330}' }, // 𑌪 .. 𑌰
    CharRange { first: '\u{11332}', last: '\u{11333}' }, // 𑌲 .. 𑌳
    CharRange { first: '\u{11335}', last: '\u{11339}' }, // 𑌵 .. 𑌹
    CharRange { first: '\u{1133b}', last: '\u{11344}' }, // 𑌻 .. 𑍄
    CharRange { first: '\u{11347}', last: '\u{11348}' }, // 𑍇 .. 𑍈
    CharRange { first: '\u{1134b}', last: '\u{1134d}' }, // 𑍋 .. 𑍍
    CharRange { first: '\u{11350}', last: '\u{11350}' }, // 𑍐 .. 𑍐
    CharRange { first: '\u{11357}', last: '\u{11357}' }, // 𑍗 .. 𑍗
    CharRange { first: '\u{1135d}', last: '\u{11363}' }, // 𑍝 .. 𑍣
    CharRange { first: '\u{11366}', last: '\u{1136c}' }, // 𑍦 .. 𑍬
    CharRange { first: '\u{11370}', last: '\u{11374}' }, // 𑍰 .. 𑍴
    CharRange { first: '\u{11400}', last: '\u{1144a}' }, // 𑐀 .. 𑑊
    CharRange { first: '\u{11450}', last: '\u{11459}' }, // 𑑐 .. 𑑙
    CharRange { first: '\u{1145e}', last: '\u{1145f}' }, // 𑑞 .. 𑑟
    CharRange { first: '\u{11480}', last: '\u{114c5}' }, // 𑒀 .. 𑓅
    CharRange { first: '\u{114c7}', last: '\u{114c7}' }, // 𑓇 .. 𑓇
    CharRange { first: '\u{114d0}', last: '\u{114d9}' }, // 𑓐 .. 𑓙
    CharRange { first: '\u{11580}', last: '\u{115b5}' }, // 𑖀 .. 𑖵
    CharRange { first: '\u{115b8}', last: '\u{115c0}' }, // 𑖸 .. 𑗀
    CharRange { first: '\u{115d8}', last: '\u{115dd}' }, // 𑗘 .. 𑗝
    CharRange { first: '\u{11600}', last: '\u{11640}' }, // 𑘀 .. 𑙀
    CharRange { first: '\u{11644}', last: '\u{11644}' }, // 𑙄 .. 𑙄
    CharRange { first: '\u{11650}', last: '\u{11659}' }, // 𑙐 .. 𑙙
    CharRange { first: '\u{11680}', last: '\u{116b8}' }, // 𑚀 .. 𑚸
    CharRange { first: '\u{116c0}', last: '\u{116c9}' }, // 𑛀 .. 𑛉
    CharRange { first: '\u{11700}', last: '\u{1171a}' }, // 𑜀 .. 𑜚
    CharRange { first: '\u{1171d}', last: '\u{1172b}' }, // 𑜝 .. 𑜫
    CharRange { first: '\u{11730}', last: '\u{11739}' }, // 𑜰 .. 𑜹
    CharRange { first: '\u{11800}', last: '\u{1183a}' }, // 𑠀 .. 𑠺
    CharRange { first: '\u{118a0}', last: '\u{118e9}' }, // 𑢠 .. 𑣩
    CharRange { first: '\u{118ff}', last: '\u{118ff}' }, // 𑣿 .. 𑣿
    CharRange { first: '\u{119a0}', last: '\u{119a7}' }, // 𑦠 .. 𑦧
    CharRange { first: '\u{119aa}', last: '\u{119d7}' }, // 𑦪 .. 𑧗
    CharRange { first: '\u{119da}', last: '\u{119e1}' }, // 𑧚 .. 𑧡
    CharRange { first: '\u{119e3}', last: '\u{119e4}' }, // 𑧣 .. 𑧤
    CharRange { first: '\u{11a00}', last: '\u{11a3e}' }, // 𑨀 .. 𑨾
    CharRange { first: '\u{11a47}', last: '\u{11a47}' }, // 𑩇 .. 𑩇
    CharRange { first: '\u{11a50}', last: '\u{11a99}' }, // 𑩐 .. 𑪙
    CharRange { first: '\u{11a9d}', last: '\u{11a9d}' }, // 𑪝 .. 𑪝
    CharRange { first: '\u{11ac0}', last: '\u{11af8}' }, // 𑫀 .. 𑫸
    CharRange { first: '\u{11c00}', last: '\u{11c08}' }, // 𑰀 .. 𑰈
    CharRange { first: '\u{11c0a}', last: '\u{11c36}' }, // 𑰊 .. 𑰶
    CharRange { first: '\u{11c38}', last: '\u{11c40}' }, // 𑰸 .. 𑱀
    CharRange { first: '\u{11c50}', last: '\u{11c59}' }, // 𑱐 .. 𑱙
    CharRange { first: '\u{11c72}', last: '\u{11c8f}' }, // 𑱲 .. 𑲏
    CharRange { first: '\u{11c92}', last: '\u{11ca7}' }, // 𑲒 .. 𑲧
    CharRange { first: '\u{11ca9}', last: '\u{11cb6}' }, // 𑲩 .. 𑲶
    CharRange { first: '\u{11d00}', last: '\u{11d06}' }, // 𑴀 .. 𑴆
    CharRange { first: '\u{11d08}', last: '\u{11d09}' }, // 𑴈 .. 𑴉
    CharRange { first: '\u{11d0b}', last: '\u{11d36}' }, // 𑴋 .. 𑴶
    CharRange { first: '\u{11d3a}', last: '\u{11d3a}' }, // 𑴺 .. 𑴺
    CharRange { first: '\u{11d3c}', last: '\u{11d3d}' }, // 𑴼 .. 𑴽
    CharRange { first: '\u{11d3f}', last: '\u{11d47}' }, // 𑴿 .. 𑵇
    CharRange { first: '\u{11d50}', last: '\u{11d59}' }, // 𑵐 .. 𑵙
    CharRange { first: '\u{11d60}', last: '\u{11d65}' }, // 𑵠 .. 𑵥
    CharRange { first: '\u{11d67}', last: '\u{11d68}' }, // 𑵧 .. 𑵨
    CharRange { first: '\u{11d6a}', last: '\u{11d8e}' }, // 𑵪 .. 𑶎
    CharRange { first: '\u{11d90}', last: '\u{11d91}' }, // 𑶐 .. 𑶑
    CharRange { first: '\u{11d93}', last: '\u{11d98}' }, // 𑶓 .. 𑶘
    CharRange { first: '\u{11da0}', last: '\u{11da9}' }, // 𑶠 .. 𑶩
    CharRange { first: '\u{11ee0}', last: '\u{11ef6}' }, // 𑻠 .. 𑻶
    CharRange { first: '\u{12000}', last: '\u{12399}' }, // 𒀀 .. 𒎙
    CharRange { first: '\u{12400}', last: '\u{1246e}' }, // 𒐀 .. 𒑮
    CharRange { first: '\u{12480}', last: '\u{12543}' }, // 𒒀 .. 𒕃
    CharRange { first: '\u{13000}', last: '\u{1342e}' }, // 𓀀 .. 𓐮
    CharRange { first: '\u{14400}', last: '\u{14646}' }, // 𔐀 .. 𔙆
    CharRange { first: '\u{16800}', last: '\u{16a38}' }, // 𖠀 .. 𖨸
    CharRange { first: '\u{16a40}', last: '\u{16a5e}' }, // 𖩀 .. 𖩞
    CharRange { first: '\u{16a60}', last: '\u{16a69}' }, // 𖩠 .. 𖩩
    CharRange { first: '\u{16ad0}', last: '\u{16aed}' }, // 𖫐 .. 𖫭
    CharRange { first: '\u{16af0}', last: '\u{16af4}' }, // 𖫰 .. 𖫴
    CharRange { first: '\u{16b00}', last: '\u{16b36}' }, // 𖬀 .. 𖬶
    CharRange { first: '\u{16b40}', last: '\u{16b43}' }, // 𖭀 .. 𖭃
    CharRange { first: '\u{16b50}', last: '\u{16b59}' }, // 𖭐 .. 𖭙
    CharRange { first: '\u{16b63}', last: '\u{16b77}' }, // 𖭣 .. 𖭷
    CharRange { first: '\u{16b7d}', last: '\u{16b8f}' }, // 𖭽 .. 𖮏
    CharRange { first: '\u{16e40}', last: '\u{16e7f}' }, // 𖹀 .. 𖹿
    CharRange { first: '\u{16f00}', last: '\u{16f4a}' }, // 𖼀 .. 𖽊
    CharRange { first: '\u{16f4f}', last: '\u{16f87}' }, // 𖽏 .. 𖾇
    CharRange { first: '\u{16f8f}', last: '\u{16f9f}' }, // 𖾏 .. 𖾟
    CharRange { first: '\u{16fe0}', last: '\u{16fe1}' }, // 𖿠 .. 𖿡
    CharRange { first: '\u{16fe3}', last: '\u{16fe3}' }, // 𖿣 .. 𖿣
    CharRange { first: '\u{17000}', last: '\u{187f7}' }, // 𗀀 .. 𘟷
    CharRange { first: '\u{18800}', last: '\u{18af2}' }, // 𘠀 .. 𘫲
    CharRange { first: '\u{1b000}', last: '\u{1b11e}' }, // 𛀀 .. 𛄞
    CharRange { first: '\u{1b150}', last: '\u{1b152}' }, // 𛅐 .. 𛅒
    CharRange { first: '\u{1b164}', last: '\u{1b167}' }, // 𛅤 .. 𛅧
    CharRange { first: '\u{1b170}', last: '\u{1b2fb}' }, // 𛅰 .. 𛋻
    CharRange { first: '\u{1bc00}', last: '\u{1bc6a}' }, // 𛰀 .. 𛱪
    CharRange { first: '\u{1bc70}', last: '\u{1bc7c}' }, // 𛱰 .. 𛱼
    CharRange { first: '\u{1bc80}', last: '\u{1bc88}' }, // 𛲀 .. 𛲈
    CharRange { first: '\u{1bc90}', last: '\u{1bc99}' }, // 𛲐 .. 𛲙
    CharRange { first: '\u{1bc9d}', last: '\u{1bc9e}' }, // 𛲝 .. 𛲞
    CharRange { first: '\u{1d165}', last: '\u{1d169}' }, // 𝅥 .. 𝅩
    CharRange { first: '\u{1d16d}', last: '\u{1d172}' }, // 𝅭 .. 𝅲
    CharRange { first: '\u{1d17b}', last: '\u{1d182}' }, // 𝅻 .. 𝆂
    CharRange { first: '\u{1d185}', last: '\u{1d18b}' }, // 𝆅 .. 𝆋
    CharRange { first: '\u{1d1aa}', last: '\u{1d1ad}' }, // 𝆪 .. 𝆭
    CharRange { first: '\u{1d242}', last: '\u{1d244}' }, // 𝉂 .. 𝉄
    CharRange { first: '\u{1d400}', last: '\u{1d454}' }, // 𝐀 .. 𝑔
    CharRange { first: '\u{1d456}', last: '\u{1d49c}' }, // 𝑖 .. 𝒜
    CharRange { first: '\u{1d49e}', last: '\u{1d49f}' }, // 𝒞 .. 𝒟
    CharRange { first: '\u{1d4a2}', last: '\u{1d4a2}' }, // 𝒢 .. 𝒢
    CharRange { first: '\u{1d4a5}', last: '\u{1d4a6}' }, // 𝒥 .. 𝒦
    CharRange { first: '\u{1d4a9}', last: '\u{1d4ac}' }, // 𝒩 .. 𝒬
    CharRange { first: '\u{1d4ae}', last: '\u{1d4b9}' }, // 𝒮 .. 𝒹
    CharRange { first: '\u{1d4bb}', last: '\u{1d4bb}' }, // 𝒻 .. 𝒻
    CharRange { first: '\u{1d4bd}', last: '\u{1d4c3}' }, // 𝒽 .. 𝓃
    CharRange { first: '\u{1d4c5}', last: '\u{1d505}' }, // 𝓅 .. 𝔅
    CharRange { first: '\u{1d507}', last: '\u{1d50a}' }, // 𝔇 .. 𝔊
    CharRange { first: '\u{1d50d}', last: '\u{1d514}' }, // 𝔍 .. 𝔔
    CharRange { first: '\u{1d516}', last: '\u{1d51c}' }, // 𝔖 .. 𝔜
    CharRange { first: '\u{1d51e}', last: '\u{1d539}' }, // 𝔞 .. 𝔹
    CharRange { first: '\u{1d53b}', last: '\u{1d53e}' }, // 𝔻 .. 𝔾
    CharRange { first: '\u{1d540}', last: '\u{1d544}' }, // 𝕀 .. 𝕄
    CharRange { first: '\u{1d546}', last: '\u{1d546}' }, // 𝕆 .. 𝕆
    CharRange { first: '\u{1d54a}', last: '\u{1d550}' }, // 𝕊 .. 𝕐
    CharRange { first: '\u{1d552}', last: '\u{1d6a5}' }, // 𝕒 .. 𝚥
    CharRange { first: '\u{1d6a8}', last: '\u{1d6c0}' }, // 𝚨 .. 𝛀
    CharRange { first: '\u{1d6c2}', last: '\u{1d6da}' }, // 𝛂 .. 𝛚
    CharRange { first: '\u{1d6dc}', last: '\u{1d6fa}' }, // 𝛜 .. 𝛺
    CharRange { first: '\u{1d6fc}', last: '\u{1d714}' }, // 𝛼 .. 𝜔
    CharRange { first: '\u{1d716}', last: '\u{1d734}' }, // 𝜖 .. 𝜴
    CharRange { first: '\u{1d736}', last: '\u{1d74e}' }, // 𝜶 .. 𝝎
    CharRange { first: '\u{1d750}', last: '\u{1d76e}' }, // 𝝐 .. 𝝮
    CharRange { first: '\u{1d770}', last: '\u{1d788}' }, // 𝝰 .. 𝞈
    CharRange { first: '\u{1d78a}', last: '\u{1d7a8}' }, // 𝞊 .. 𝞨
    CharRange { first: '\u{1d7aa}', last: '\u{1d7c2}' }, // 𝞪 .. 𝟂
    CharRange { first: '\u{1d7c4}', last: '\u{1d7cb}' }, // 𝟄 .. 𝟋
    CharRange { first: '\u{1d7ce}', last: '\u{1d7ff}' }, // 𝟎 .. 𝟿
    CharRange { first: '\u{1da00}', last: '\u{1da36}' }, // 𝨀 .. 𝨶
    CharRange { first: '\u{1da3b}', last: '\u{1da6c}' }, // 𝨻 .. 𝩬
    CharRange { first: '\u{1da75}', last: '\u{1da75}' }, // 𝩵 .. 𝩵
    CharRange { first: '\u{1da84}', last: '\u{1da84}' }, // 𝪄 .. 𝪄
    CharRange { first: '\u{1da9b}', last: '\u{1da9f}' }, // 𝪛 .. 𝪟
    CharRange { first: '\u{1daa1}', last: '\u{1daaf}' }, // 𝪡 .. 𝪯
    CharRange { first: '\u{1e000}', last: '\u{1e006}' }, // 𞀀 .. 𞀆
    CharRange { first: '\u{1e008}', last: '\u{1e018}' }, // 𞀈 .. 𞀘
    CharRange { first: '\u{1e01b}', last: '\u{1e021}' }, // 𞀛 .. 𞀡
    CharRange { first: '\u{1e023}', last: '\u{1e024}' }, // 𞀣 .. 𞀤
    CharRange { first: '\u{1e026}', last: '\u{1e02a}' }, // 𞀦 .. 𞀪
    CharRange { first: '\u{1e100}', last: '\u{1e12c}' }, // 𞄀 .. 𞄬
    CharRange { first: '\u{1e130}', last: '\u{1e13d}' }, // 𞄰 .. 𞄽
    CharRange { first: '\u{1e140}', last: '\u{1e149}' }, // 𞅀 .. 𞅉
    CharRange { first: '\u{1e14e}', last: '\u{1e14e}' }, // 𞅎 .. 𞅎
    CharRange { first: '\u{1e2c0}', last: '\u{1e2f9}' }, // 𞋀 .. 𞋹
    CharRange { first: '\u{1e800}', last: '\u{1e8c4}' }, // 𞠀 .. 𞣄
    CharRange { first: '\u{1e8d0}', last: '\u{1e8d6}' }, // 𞣐 .. 𞣖
    CharRange { first: '\u{1e900}', last: '\u{1e94b}' }, // 𞤀 .. 𞥋
    CharRange { first: '\u{1e950}', last: '\u{1e959}' }, // 𞥐 .. 𞥙
    CharRange { first: '\u{1ee00}', last: '\u{1ee03}' }, // 𞸀 .. 𞸃
    CharRange { first: '\u{1ee05}', last: '\u{1ee1f}' }, // 𞸅 .. 𞸟
    CharRange { first: '\u{1ee21}', last: '\u{1ee22}' }, // 𞸡 .. 𞸢
    CharRange { first: '\u{1ee24}', last: '\u{1ee24}' }, // 𞸤 .. 𞸤
    CharRange { first: '\u{1ee27}', last: '\u{1ee27}' }, // 𞸧 .. 𞸧
    CharRange { first: '\u{1ee29}', last: '\u{1ee32}' }, // 𞸩 .. 𞸲
    CharRange { first: '\u{1ee34}', last: '\u{1ee37}' }, // 𞸴 .. 𞸷
    CharRange { first: '\u{1ee39}', last: '\u{1ee39}' }, // 𞸹 .. 𞸹
    CharRange { first: '\u{1ee3b}', last: '\u{1ee3b}' }, // 𞸻 .. 𞸻
    CharRange { first: '\u{1ee42}', last: '\u{1ee42}' }, // 𞹂 .. 𞹂
    CharRange { first: '\u{1ee47}', last: '\u{1ee47}' }, // 𞹇 .. 𞹇
    CharRange { first: '\u{1ee49}', last: '\u{1ee49}' }, // 𞹉 .. 𞹉
    CharRange { first: '\u{1ee4b}', last: '\u{1ee4b}' }, // 𞹋 .. 𞹋
    CharRange { first: '\u{1ee4d}', last: '\u{1ee4f}' }, // 𞹍 .. 𞹏
    CharRange { first: '\u{1ee51}', last: '\u{1ee52}' }, // 𞹑 .. 𞹒
    CharRange { first: '\u{1ee54}', last: '\u{1ee54}' }, // 𞹔 .. 𞹔
    CharRange { first: '\u{1ee57}', last: '\u{1ee57}' }, // 𞹗 .. 𞹗
    CharRange { first: '\u{1ee59}', last: '\u{1ee59}' }, // 𞹙 .. 𞹙
    CharRange { first: '\u{1ee5b}', last: '\u{1ee5b}' }, // 𞹛 .. 𞹛
    CharRange { first: '\u{1ee5d}', last: '\u{1ee5d}' }, // 𞹝 .. 𞹝
    CharRange { first: '\u{1ee5f}', last: '\u{1ee5f}' }, // 𞹟 .. 𞹟
    CharRange { first: '\u{1ee61}', last: '\u{1ee62}' }, // 𞹡 .. 𞹢
    CharRange { first: '\u{1ee64}', last: '\u{1ee64}' }, // 𞹤 .. 𞹤
    CharRange { first: '\u{1ee67}', last: '\u{1ee6a}' }, // 𞹧 .. 𞹪
    CharRange { first: '\u{1ee6c}', last: '\u{1ee72}' }, // 𞹬 .. 𞹲
    CharRange { first: '\u{1ee74}', last: '\u{1ee77}' }, // 𞹴 .. 𞹷
    CharRange { first: '\u{1ee79}', last: '\u{1ee7c}' }, // 𞹹 .. 𞹼
    CharRange { first: '\u{1ee7e}', last: '\u{1ee7e}' }, // 𞹾 .. 𞹾
    CharRange { first: '\u{1ee80}', last: '\u{1ee89}' }, // 𞺀 .. 𞺉
    CharRange { first: '\u{1ee8b}', last: '\u{1ee9b}' }, // 𞺋 .. 𞺛
    CharRange { first: '\u{1eea1}', last: '\u{1eea3}' }, // 𞺡 .. 𞺣
    CharRange { first: '\u{1eea5}', last: '\u{1eea9}' }, // 𞺥 .. 𞺩
    CharRange { first: '\u{1eeab}', last: '\u{1eebb}' }, // 𞺫 .. 𞺻
    CharRange { first: '\u{20000}', last: '\u{2a6d6}' }, // 𠀀 .. 𪛖
    CharRange { first: '\u{2a700}', last: '\u{2b734}' }, // 𪜀 .. 𫜴
    CharRange { first: '\u{2b740}', last: '\u{2b81d}' }, // 𫝀 .. 𫠝
    CharRange { first: '\u{2b820}', last: '\u{2cea1}' }, // 𫠠 .. 𬺡
    CharRange { first: '\u{2ceb0}', last: '\u{2ebe0}' }, // 𬺰 .. 𮯠
    CharRange { first: '\u{2f800}', last: '\u{2fa1d}' }, // 丽 .. 𪘀
    CharRange { first: '\u{e0100}', last: '\u{e01ef}' }, // 󠄀 .. 󠇯
];
